package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by driving the upstream TuiAltScreen with a
// fake recording terminal and scripted content/input steps, then dumping the
// concatenated writes per step (tui/testdata/altscreen_golden.txt).

type altScreenStep struct {
	Lines   []string `json:"lines"`
	Inputs  []string `json:"inputs"`
	Flashes []string `json:"flashes"`
	Columns *int     `json:"columns"`
	Rows    *int     `json:"rows"`
}

type altScreenSpec struct {
	Steps         []altScreenStep `json:"steps"`
	Indicator     bool            `json:"indicator"`
	CopySelection bool            `json:"copySelection"`
	Stop          bool            `json:"stop"`
}

// TestAltScreenAgainstUpstreamGolden replays the upstream write streams.
func TestAltScreenAgainstUpstreamGolden(t *testing.T) {
	golden := loadAltScreenGolden(t)
	data, err := os.ReadFile("testdata/altscreen_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]altScreenSpec{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		spec := corpus[label]
		terminal := &recordingTerminal{width: 24, height: 6}
		options := AltScreenOptions{}
		if spec.Indicator {
			options.ScrollToEndIndicator = func() string { return " ↓ Jump to latest message " }
		}
		var copied []string
		if spec.CopySelection {
			options.CopySelection = func(text string) (bool, bool, string) {
				copied = append(copied, text)
				return true, true, ""
			}
		}
		screen := NewAltScreen(terminal, false, t.TempDir(), options)
		screen.DisableAutoRender()
		component := &scriptedComponent{}
		screen.AddChild(component)

		terminal.writes = nil
		inputHandler := func(data string) { screen.HandleTerminalInput(data) }
		screen.Start()

		var steps []string
		steps = append(steps, strings.Join(terminal.writes, ""))

		for _, step := range spec.Steps {
			if step.Lines != nil {
				component.lines = step.Lines
			}
			if step.Columns != nil {
				terminal.width = *step.Columns
			}
			if step.Rows != nil {
				terminal.height = *step.Rows
			}
			for _, input := range step.Inputs {
				inputHandler(input)
			}
			for _, flash := range step.Flashes {
				screen.Flash(flash, 0)
			}
			terminal.writes = nil
			screen.RenderNow(false)
			steps = append(steps, strings.Join(terminal.writes, ""))
		}
		if spec.Stop {
			terminal.writes = nil
			screen.Stop(TuiStopOptions{})
			steps = append(steps, strings.Join(terminal.writes, ""))
		}

		want, ok := golden[label]
		if !ok {
			t.Fatalf("missing golden %q", label)
		}
		var wantSteps []string
		if err := json.Unmarshal([]byte(want), &wantSteps); err != nil {
			t.Fatalf("bad golden %q: %v", label, err)
		}
		if len(steps) != len(wantSteps) {
			t.Fatalf("%s: %d steps, want %d", label, len(steps), len(wantSteps))
		}
		for index := range steps {
			if steps[index] != wantSteps[index] {
				t.Fatalf("%s step %d:\n got %q\nwant %q", label, index, steps[index], wantSteps[index])
			}
		}
		_ = copied
	}
}

func loadAltScreenGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/altscreen_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "alt ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

// TestAltScreenSelectionHelpers covers the selection text extraction and
// highlight application without a golden.
func TestAltScreenSelectionHelpers(t *testing.T) {
	terminal := &recordingTerminal{width: 20, height: 6}
	screen := NewAltScreen(terminal, false, t.TempDir(), AltScreenOptions{})
	screen.DisableAutoRender()
	component := &scriptedComponent{lines: []string{"hello world"}}
	screen.AddChild(component)
	screen.Start()
	screen.RenderNow(false)

	// Click and drag selects a range.
	pressed := func(data string) { screen.HandleTerminalInput(data) }
	pressed("\x1b[<0;1;1M")
	pressed("\x1b[<32;6;1M")
	pressed("\x1b[<0;6;1m")
	if !screen.HasActiveSelection() {
		t.Fatal("no active selection")
	}
	screen.SetCopyOnSelect(false)

	// A single click clears the selection.
	pressed("\x1b[<0;1;1M")
	pressed("\x1b[<0;1;1m")
	if screen.HasActiveSelection() {
		t.Fatal("selection not cleared")
	}
}

// TestAltScreenSearchOverlay covers the search toggle and query flow.
func TestAltScreenSearchOverlay(t *testing.T) {
	terminal := &recordingTerminal{width: 30, height: 8}
	screen := NewAltScreen(terminal, false, t.TempDir(), AltScreenOptions{})
	screen.DisableAutoRender()
	component := &scriptedComponent{lines: []string{"alpha beta", "gamma alpha"}}
	screen.AddChild(component)
	screen.Start()
	screen.RenderNow(false)

	screen.HandleTerminalInput("\x1b[102;6u") // ctrl+shift+f
	if screen.activeSearch == nil {
		t.Fatal("search not opened")
	}
	for _, character := range "alpha" {
		screen.HandleTerminalInput(string(character))
	}
	screen.RenderNow(false)
	if len(screen.activeSearch.Matches) != 2 {
		t.Fatalf("matches = %d", len(screen.activeSearch.Matches))
	}
	// Navigating to a match reveals it, which disables follow-end.
	screen.HandleTerminalInput("\r")
	screen.RenderNow(false)
	if selected := screen.activeSearch.SelectedIndex; selected < 0 {
		t.Fatalf("no selected match after navigate: %d", selected)
	}
	screen.HandleTerminalInput("\x1b")
	if screen.activeSearch != nil {
		t.Fatal("search not closed")
	}
}
