package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream alt-screen search
// module with Node (tui/testdata/altsearch_golden.txt).

func loadAltSearchGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/altsearch_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "as ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

type altSearchSpec struct {
	Lines     []string `json:"lines"`
	Query     string   `json:"query"`
	Component bool     `json:"component"`
	Focused   bool     `json:"focused"`
	Width     int      `json:"width"`
	Result    []int    `json:"result"`
	Hover     *int     `json:"hover"`
}

// TestAltSearchAgainstUpstreamGolden replays the upstream search corpus.
func TestAltSearchAgainstUpstreamGolden(t *testing.T) {
	golden := loadAltSearchGolden(t)
	data, err := os.ReadFile("testdata/altsearch_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]altSearchSpec{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		spec := corpus[label]

		if spec.Lines != nil {
			matches := FindAltScreenSearchMatches(spec.Lines, spec.Query)
			segments := make([][]AltScreenSearchSegment, 0, len(matches))
			keys := make([]string, 0, len(matches))
			for _, match := range matches {
				segments = append(segments, match.Segments)
				keys = append(keys, GetAltScreenSearchMatchKey(match))
			}
			checkAltSearchGolden(t, golden, label+" matches", segments)
			checkAltSearchGolden(t, golden, label+" keys", keys)

			index := &AltScreenSearchIndex{}
			first := index.Search(spec.Lines, spec.Query)
			second := index.Search(spec.Lines, spec.Query)
			changed := index.Search(spec.Lines, spec.Query+"!")
			checkAltSearchGolden(t, golden, label+" index", []bool{first.Changed, second.Changed, changed.Changed})
		}

		if spec.Component {
			component := NewAltScreenSearchComponent(nil, nil)
			component.SetFocused(spec.Focused)
			for _, character := range spec.Query {
				component.HandleInput(string(character))
			}
			if len(spec.Result) == 2 {
				component.SetResult(spec.Result[0], spec.Result[1])
			}
			if spec.Hover != nil {
				component.SetHoveredNavigationDirection(*spec.Hover, true)
			}
			checkAltSearchGolden(t, golden, label+" render@"+itoa(spec.Width), component.Render(spec.Width))
			navResults := make([]any, 0, 3)
			for _, probe := range [][2]int{{2, 4}, {2, 20}, {1, 4}} {
				direction, ok := component.GetNavigationDirectionAt(probe[0], probe[1])
				if !ok {
					navResults = append(navResults, nil)
					continue
				}
				navResults = append(navResults, direction)
			}
			checkAltSearchGolden(t, golden, label+" nav", navResults)
		}
	}
}

func checkAltSearchGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// mustParseJSON parses golden JSON text for stable comparison.
func mustParseJSON(t *testing.T, text string) any {
	t.Helper()
	var parsed any
	if err := json.Unmarshal([]byte(text), &parsed); err != nil {
		t.Fatalf("bad JSON %q: %v", text, err)
	}
	return parsed
}
