package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

// The golden file is generated by driving the upstream Editor with scripted
// input sequences and dumping the text, cursor, render, and expanded text.
// See tui/testdata/editor_corpus.json.

type editorGolden struct {
	values map[string]string
}

func loadEditorGolden(t *testing.T) *editorGolden {
	t.Helper()
	file, err := os.Open("testdata/editor_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "ed ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return &editorGolden{values: values}
}

func (g *editorGolden) check(t *testing.T, label string, got any) {
	t.Helper()
	want, ok := g.values[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	rendered := renderGoldenValue(got)
	if rendered != want {
		t.Fatalf("%s:\n got %s\nwant %s", label, rendered, want)
	}
}

type editorSpec struct {
	Text     *string  `json:"text"`
	Inputs   []string `json:"inputs"`
	Width    int      `json:"width"`
	Rows     int      `json:"rows"`
	History  []string `json:"history"`
	Focused  bool     `json:"focused"`
	Expanded bool     `json:"expanded"`
	Options  *struct {
		PaddingX               int `json:"paddingX"`
		AutocompleteMaxVisible int `json:"autocompleteMaxVisible"`
	} `json:"options"`
}

type editorHost struct {
	rows int
}

func (h *editorHost) Rows() int                { return h.rows }
func (h *editorHost) RequestRender(force bool) {}

func editorTestTheme() EditorTheme {
	return EditorTheme{
		BorderColor: mdTag("bc"),
		SelectList: SelectListTheme{
			SelectedPrefix: mdTag("sp"),
			SelectedText:   mdTag("st"),
			Description:    mdTag("sd"),
			ScrollInfo:     mdTag("si"),
			NoMatch:        mdTag("sn"),
		},
	}
}

// TestEditorAgainstUpstreamGolden replays the upstream editor corpus.
func TestEditorAgainstUpstreamGolden(t *testing.T) {
	golden := loadEditorGolden(t)
	data, err := os.ReadFile("testdata/editor_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]editorSpec{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		spec := corpus[label]
		rows := spec.Rows
		if rows == 0 {
			rows = 10
		}
		host := &editorHost{rows: rows}
		options := EditorOptions{}
		if spec.Options != nil {
			options.PaddingX = spec.Options.PaddingX
			options.AutocompleteMaxVisible = spec.Options.AutocompleteMaxVisible
		}
		editor := NewEditor(host, editorTestTheme(), options)
		editor.SetFocused(spec.Focused)
		for _, entry := range spec.History {
			editor.AddToHistory(entry)
		}
		if spec.Text != nil {
			editor.SetText(*spec.Text)
		}
		for _, input := range spec.Inputs {
			switch {
			case strings.HasPrefix(input, "MOUSE:"):
				parts := strings.Split(input, ":")
				x, _ := strconv.Atoi(parts[1])
				y, _ := strconv.Atoi(parts[2])
				width, _ := strconv.Atoi(parts[3])
				editor.HandleMouse(TuiMouseEvent{
					Type: MouseClick, Button: MouseButtonLeft,
					X: x, Y: y, Width: width, Height: 10, ScreenX: x, ScreenY: y,
				})
			case strings.HasPrefix(input, "SETTEXT:"):
				editor.SetText(input[len("SETTEXT:"):])
			default:
				editor.HandleInput(input)
			}
		}

		width := spec.Width
		if width == 0 {
			width = 30
		}
		golden.check(t, label+" text", mustJSON(editor.GetText()))
		// Upstream cursors are UTF-16 code-unit offsets; the Go port uses byte
		// offsets (divergence D61), so the golden cursor is translated.
		wantCursor, ok := golden.values[label+" cursor"]
		if !ok {
			t.Fatalf("missing golden %q", label+" cursor")
		}
		cursorParts := strings.Split(wantCursor, ",")
		wantLine, _ := strconv.Atoi(cursorParts[0])
		wantColJS, _ := strconv.Atoi(cursorParts[1])
		line, col := editor.Cursor()
		lines := editor.GetLines()
		wantCol := wantColJS
		if wantLine >= 0 && wantLine < len(lines) {
			wantCol = jsOffsetToByteOffset(lines[wantLine], wantColJS)
		}
		if line != wantLine || col != wantCol {
			t.Fatalf("%s cursor: got %d,%d want %d,%d", label, line, col, wantLine, wantCol)
		}
		golden.check(t, label+" render@"+strconv.Itoa(width), normalizeSlice(editor.Render(width)))
		if spec.Expanded {
			golden.check(t, label+" expanded", mustJSON(editor.GetExpandedText()))
		}
	}
}

// normalizeSlice converts a nil slice into an empty one so JSON output matches
// upstream's empty arrays.
func normalizeSlice(lines []string) []string {
	if lines == nil {
		return []string{}
	}
	return lines
}

// TestEditorSubmitReentrancy guards D136: the submit handler runs outside the
// editor lock, so it may call back into the editor without deadlocking.
func TestEditorSubmitReentrancy(t *testing.T) {
	editor := NewEditor(&editorHost{rows: 10}, editorTestTheme(), EditorOptions{})
	var submitted []string
	editor.OnSubmit = func(text string) {
		submitted = append(submitted, text)
		// The interactive submit handler clears and reads the editor.
		editor.SetText("")
		_ = editor.GetText()
		editor.AddToHistory(text)
	}

	done := make(chan struct{})
	go func() {
		defer close(done)
		editor.SetText("hello")
		editor.HandleInput("\r")
	}()

	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("HandleInput deadlocked in OnSubmit")
	}
	if len(submitted) != 1 || submitted[0] != "hello" {
		t.Fatalf("submitted = %v", submitted)
	}
	if editor.GetText() != "" {
		t.Fatalf("editor = %q", editor.GetText())
	}
}
