package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream Box/Input components
// with Node. See tui/testdata/input_golden.txt.

func loadInputGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/input_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkInputGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	got = normalizeEmptySlice(got)
	if rendered := renderGoldenValue(got); rendered != want {
		t.Fatalf("%s:\n got %s\nwant %s", label, rendered, want)
	}
}

// TestBoxAgainstUpstreamGolden verifies the box padding and background.
func TestBoxAgainstUpstreamGolden(t *testing.T) {
	golden := loadInputGolden(t)

	box1 := NewBox(1, 1, nil)
	box1.AddChild(probe("hi"))
	checkInputGolden(t, golden, "box-pad", box1.Render(6))

	box2 := NewBox(2, 0, func(text string) string { return "\x1b[44m" + text + "\x1b[49m" })
	box2.AddChild(probe("ab"))
	checkInputGolden(t, golden, "box-bg", box2.Render(7))

	box3 := NewBox(1, 0, nil)
	checkInputGolden(t, golden, "box-empty", box3.Render(5))
	box3.AddChild(probe("x"))
	checkInputGolden(t, golden, "box-one", box3.Render(4))
	box3.RemoveChild(box3.Children[0])
	checkInputGolden(t, golden, "box-removed", box3.Render(4))

	box4 := NewBox(0, 1, nil)
	box4.AddChild(probe("aa", "bb"))
	checkInputGolden(t, golden, "box-vpad", box4.Render(3))
}

// TestInputAgainstUpstreamGolden replays scripted input sequences.
func TestInputAgainstUpstreamGolden(t *testing.T) {
	golden := loadInputGolden(t)

	cases := []struct {
		label string
		ops   []string
		width int
	}{
		{"type", []string{"h", "i"}, 20},
		{"left", []string{"a", "b", "c", "\x1b[D"}, 20},
		{"right", []string{"a", "\x1b[D", "\x1b[C"}, 20},
		{"home-end", []string{"a", "b", "c", "\x01", "\x05"}, 20},
		{"backspace", []string{"a", "b", "\x7f"}, 20},
		{"delete", []string{"a", "b", "\x01", "\x1b[3~"}, 20},
		{"ctrl-w", []string{"o", "n", "e", " ", "t", "w", "o", "\x17"}, 20},
		{"ctrl-u", []string{"a", "b", "c", "\x15"}, 20},
		{"ctrl-k", []string{"a", "b", "c", "\x01", "\x0b"}, 20},
		{"ctrl-y", []string{"a", "b", "c", "\x15", "\x19"}, 20},
		{"ctrl-y2", []string{"x", "y", "\x15", "\x19", "\x19"}, 20},
		{"alt-d", []string{"o", "n", "e", " ", "t", "w", "o", "\x1bd"}, 20},
		{"alt-left", []string{"o", "n", "e", " ", "t", "w", "o", "\x1b[D", "\x1b[D", "\x1b[D", "\x1b[D", "\x1b[D"}, 20},
		{"undo", []string{"a", "b", "c", "\x1f"}, 20},
		{"paste", []string{"x", "\x1b[200~hello\nworld\ttab\x1b[201~", "y"}, 20},
		{"kitty", []string{"\x1b[97u", "\x1b[98u"}, 20},
		{"wide", []string{"日", "本", "語"}, 20},
		{"scroll", []string{"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"}, 10},
		{"scroll-end", []string{"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"}, 10},
		{"control-only", []string{"\x01"}, 20},
		{"submit", []string{"a"}, 20},
		{"yank-pop", []string{"a", "b", "\x15", "c", "d", "\x15", "\x19", "\x1by"}, 20},
		{"delete-word-fwd", []string{"a", "b", "c", " ", "d", "\x01", "\x1bd"}, 20},
		{"placeholder", nil, 10},
	}

	for _, tc := range cases {
		input := NewInput(InputOptions{Prompt: "> "})
		for _, op := range tc.ops {
			input.HandleInput(op)
		}
		want, ok := golden["input "+tc.label]
		if !ok {
			t.Fatalf("missing golden input %q", tc.label)
		}
		wantValue, wantCursorJS, wantRender := parseInputGolden(t, want)

		if got := mustJSON(input.Value()); got != wantValue {
			t.Fatalf("input %s value:\n got %s\nwant %s", tc.label, got, wantValue)
		}
		if got := mustJSON(input.Render(tc.width)); got != wantRender {
			t.Fatalf("input %s render:\n got %s\nwant %s", tc.label, got, wantRender)
		}
		// Upstream cursors are UTF-16 code-unit offsets; the Go port uses byte
		// offsets (divergence D61), so the golden cursor is translated.
		wantCursor := jsOffsetToByteOffset(input.Value(), wantCursorJS)
		if input.cursor != wantCursor {
			t.Fatalf("input %s cursor = %d want %d", tc.label, input.cursor, wantCursor)
		}
	}
}

// parseInputGolden splits "value=<json> cursor=<n> render=<json>".
func parseInputGolden(t *testing.T, golden string) (value string, cursor int, rendering string) {
	t.Helper()
	valuePart, rest, ok := strings.Cut(golden, " cursor=")
	if !ok {
		t.Fatalf("bad input golden %q", golden)
	}
	cursorPart, renderPart, ok := strings.Cut(rest, " render=")
	if !ok {
		t.Fatalf("bad input golden %q", golden)
	}
	value = strings.TrimPrefix(valuePart, "value=")
	cursor = atoiSafe(cursorPart)
	rendering = strings.TrimPrefix(renderPart, "render=")
	return value, cursor, rendering
}

// jsOffsetToByteOffset translates a UTF-16 code-unit offset into the
// corresponding byte offset in the UTF-8 string (divergence D61).
func jsOffsetToByteOffset(value string, jsOffset int) int {
	units := 0
	for index, r := range value {
		if units >= jsOffset {
			return index
		}
		if r > 0xFFFF {
			units += 2
		} else {
			units++
		}
	}
	return len(value)
}

// normalizeEmptySlice turns a nil slice into an empty one so JSON output
// matches upstream's empty arrays.
func normalizeEmptySlice(value any) any {
	switch typed := value.(type) {
	case []string:
		if typed == nil {
			return []string{}
		}
	}
	return value
}

// mustJSON encodes without HTML escaping, matching JSON.stringify (Go escapes
// <, > and & by default).
func mustJSON(value any) string {
	var buffer strings.Builder
	encoder := json.NewEncoder(&buffer)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(value); err != nil {
		panic(err)
	}
	return strings.TrimSuffix(buffer.String(), "\n")
}

// TestInputRenderingAgainstUpstreamGolden covers the placeholder, focus, and
// narrow-width renders.
func TestInputRenderingAgainstUpstreamGolden(t *testing.T) {
	golden := loadInputGolden(t)

	placeholder := NewInput(InputOptions{Prompt: "> ", Placeholder: "Search"})
	checkInputGolden(t, golden, "input placeholder-render",
		"render="+mustJSON(placeholder.Render(12)))

	placeholderFocused := NewInput(InputOptions{Prompt: "> ", Placeholder: "Search"})
	placeholderFocused.SetFocused(true)
	checkInputGolden(t, golden, "input placeholder-focused",
		"render="+mustJSON(placeholderFocused.Render(12)))

	focused := NewInput(InputOptions{Prompt: "> "})
	focused.SetFocused(true)
	focused.HandleInput("a")
	checkInputGolden(t, golden, "input focused", "render="+mustJSON(focused.Render(12)))

	narrow := NewInput(InputOptions{Prompt: "> "})
	narrow.HandleInput("hello")
	checkInputGolden(t, golden, "input narrow", "render="+mustJSON(narrow.Render(4)))
	checkInputGolden(t, golden, "input tiny", "render="+mustJSON(narrow.Render(2)))
}

// TestInputCallbacks verifies submit, escape, mouse placement, and paste.
func TestInputCallbacks(t *testing.T) {
	submitted := ""
	input := NewInput(InputOptions{Prompt: "> "})
	input.OnSubmit = func(value string) { submitted = value }
	input.HandleInput("a")
	input.HandleInput("\r")
	if submitted != "a" {
		t.Fatalf("submitted = %q", submitted)
	}

	escaped := false
	input.OnEscape = func() { escaped = true }
	input.HandleInput("\x1b")
	if !escaped {
		t.Fatal("escape not dispatched")
	}

	// Mouse press on column 3 places the cursor after two cells of "> abcd"
	// (prompt width 2, so visible column 1).
	mouse := NewInput(InputOptions{Prompt: "> "})
	mouse.SetValue("abcd")
	result := mouse.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, X: 3, Y: 0, Width: 20})
	if result == nil || !result.Handled || !result.Focus {
		t.Fatalf("mouse result = %+v", result)
	}
	if mouse.cursor != 1 {
		t.Fatalf("cursor = %d", mouse.cursor)
	}
	// Presses on other rows or buttons are ignored.
	if got := mouse.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, X: 3, Y: 1}); got != nil {
		t.Fatalf("row press = %+v", got)
	}
	if got := mouse.HandleMouse(TuiMouseEvent{Type: MouseMove, Button: MouseButtonLeft, X: 3, Y: 0}); got != nil {
		t.Fatalf("move = %+v", got)
	}

	// Paste splits across chunks and keeps only the trailing input.
	paste := NewInput(InputOptions{Prompt: "> "})
	paste.HandleInput("\x1b[200~hello")
	paste.HandleInput(" world\x1b[201~x")
	if paste.Value() != "hello worldx" {
		t.Fatalf("paste value = %q", paste.Value())
	}

	// SetValue clamps the cursor.
	clamp := NewInput(InputOptions{})
	clamp.HandleInput("abcd")
	clamp.SetValue("a")
	if clamp.cursor != 1 {
		t.Fatalf("cursor = %d", clamp.cursor)
	}
	if clamp.IsFocused() {
		t.Fatal("must start unfocused")
	}
}

// TestWordSegmentsAgainstUpstreamGolden verifies the word segmentation rules.
func TestWordSegmentsAgainstUpstreamGolden(t *testing.T) {
	golden := loadWordsGolden(t)

	for _, label := range golden.segmentOrder {
		want := golden.segments[label]
		segments := WordSegments(label)
		got := make([][2]any, 0, len(segments))
		for _, segment := range segments {
			got = append(got, [2]any{segment.Segment, segment.IsWordLike})
		}
		if rendered, wantRendered := mustJSON(got), mustJSON(want); rendered != wantRendered {
			t.Fatalf("seg %q:\n got %s\nwant %s", label, rendered, wantRendered)
		}
		// Indices must be consistent with the segments.
		offset := 0
		for _, segment := range segments {
			if segment.Index != offset {
				t.Fatalf("segment %q index = %d want %d", segment.Segment, segment.Index, offset)
			}
			offset += len(segment.Segment)
		}
	}
}

type wordsGolden struct {
	segmentOrder []string
	segments     map[string][][2]any
	backward     map[string]int
	forward      map[string]int
}

func loadWordsGolden(t *testing.T) *wordsGolden {
	t.Helper()
	file, err := os.Open("testdata/words_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	golden := &wordsGolden{
		segments: map[string][][2]any{},
		backward: map[string]int{},
		forward:  map[string]int{},
	}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		left, right := parts[0], parts[1]
		switch {
		case strings.HasPrefix(left, "seg "):
			var text string
			if err := json.Unmarshal([]byte(strings.TrimPrefix(left, "seg ")), &text); err != nil {
				t.Fatalf("bad seg %q: %v", line, err)
			}
			var segments [][2]any
			if err := json.Unmarshal([]byte(right), &segments); err != nil {
				t.Fatalf("bad segments %q: %v", line, err)
			}
			golden.segmentOrder = append(golden.segmentOrder, text)
			golden.segments[text] = segments
		case strings.HasPrefix(left, "back "), strings.HasPrefix(left, "fwd "):
			isBackward := strings.HasPrefix(left, "back ")
			body := strings.TrimPrefix(strings.TrimPrefix(left, "back "), "fwd ")
			quoteEnd := strings.LastIndex(body, `" `)
			if quoteEnd == -1 {
				t.Fatalf("bad navigation line %q", line)
			}
			var text string
			if err := json.Unmarshal([]byte(body[:quoteEnd+1]), &text); err != nil {
				t.Fatalf("bad text %q: %v", line, err)
			}
			var cursor int
			if err := json.Unmarshal([]byte(body[quoteEnd+2:]), &cursor); err != nil {
				t.Fatalf("bad cursor %q: %v", line, err)
			}
			var result int
			if err := json.Unmarshal([]byte(right), &result); err != nil {
				t.Fatalf("bad result %q: %v", line, err)
			}
			key := navigationKey(text, cursor)
			if isBackward {
				golden.backward[key] = result
			} else {
				golden.forward[key] = result
			}
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return golden
}

func navigationKey(text string, cursor int) string {
	return text + "\x00" + renderGoldenValue(cursor)
}

// TestWordNavigationAgainstUpstreamGolden verifies the word navigation
// functions. Cursors are JS string offsets; the corpus is ASCII plus accented
// characters where both agree (divergence D58 for full UAX #29).
func TestWordNavigationAgainstUpstreamGolden(t *testing.T) {
	golden := loadWordsGolden(t)

	for _, label := range golden.segmentOrder {
		runes := []rune(label)
		for cursor := 0; cursor <= len(runes); cursor++ {
			key := navigationKey(label, cursor)
			wantBackward, hasBackward := golden.backward[key]
			if !hasBackward {
				continue
			}
			if got := FindWordBackward(label, cursor); got != wantBackward {
				t.Fatalf("FindWordBackward(%q, %d) = %d want %d", label, cursor, got, wantBackward)
			}
			wantForward := golden.forward[key]
			if got := FindWordForward(label, cursor); got != wantForward {
				t.Fatalf("FindWordForward(%q, %d) = %d want %d", label, cursor, got, wantForward)
			}
		}
	}
}
