package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream keys.ts implementation
// with Node (see the round notes): for each input the upstream parseKey,
// decodePrintableKey/decodeKittyPrintable results and every matching key id
// are recorded, once with the Kitty protocol inactive and once active. The Go
// port must reproduce the same results, including the negatives (a key id not
// listed must not match).

var goldenKeyIDs = []string{
	"escape", "esc", "tab", "shift+tab", "enter", "return", "shift+enter", "alt+enter",
	"space", "ctrl+space", "alt+space", "backspace", "ctrl+backspace", "alt+backspace",
	"up", "down", "left", "right", "alt+up", "alt+down", "alt+left", "alt+right",
	"ctrl+up", "ctrl+down", "ctrl+left", "ctrl+right", "shift+up", "shift+down", "shift+left", "shift+right",
	"insert", "delete", "clear", "home", "end", "pageup", "pagedown",
	"shift+insert", "shift+delete", "ctrl+insert", "ctrl+delete", "shift+clear", "ctrl+clear",
	"shift+home", "shift+end", "shift+pageup", "shift+pagedown",
	"ctrl+home", "ctrl+end", "ctrl+pageup", "ctrl+pagedown",
	"f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
	"a", "ctrl+a", "ctrl+c", "ctrl+z", "ctrl+shift+p", "ctrl+alt+a", "alt+a", "shift+a",
	"ctrl+d", "ctrl+/", "ctrl+[", "ctrl+\\", "ctrl+]", "ctrl+-", "ctrl+_", "shift+1", "1",
	"super+k", "ctrl+super+k", "shift+ctrl+d", "shift+ctrl+p", "alt+shift+p",
}

// decodeJSONString decodes a JSON string literal from the golden file.
func decodeJSONString(t *testing.T, literal string) (string, bool) {
	t.Helper()
	if literal == "undefined" {
		return "", false
	}
	var value string
	if err := json.Unmarshal([]byte(literal), &value); err != nil {
		t.Fatalf("bad JSON literal %q: %v", literal, err)
	}
	return value, true
}

// TestKeysAgainstUpstreamGolden verifies parseKey, decodePrintableKey, and
// matchesKey against the upstream-generated golden matrix.
func TestKeysAgainstUpstreamGolden(t *testing.T) {
	file, err := os.Open("testdata/keys_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	type expectations struct {
		parseKey    string
		hasParseKey bool
		decode      string
		hasDecode   bool
		kittyDecode string
		hasKittyDec bool
		matches     map[string]bool
	}

	// expected is keyed by kittyState + "\x00" + data.
	expected := map[string]*expectations{}
	var order []string

	kittyActive := false
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "# kitty=") {
			kittyActive = strings.TrimPrefix(line, "# kitty=") == "true"
			continue
		}
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line: %q", line)
		}
		command, dataLiteral, extra := splitGoldenLeft(parts[0])
		right := parts[1]

		switch command {
		case "parseKey":
			data, _ := decodeJSONString(t, dataLiteral)
			key := keyOf(kittyActive, data)
			entry, ok := expected[key]
			if !ok {
				entry = &expectations{matches: map[string]bool{}}
				expected[key] = entry
				order = append(order, key)
			}
			value, ok := decodeJSONString(t, right)
			entry.parseKey, entry.hasParseKey = value, ok

		case "decode":
			data, _ := decodeJSONString(t, dataLiteral)
			key := keyOf(kittyActive, data)
			entry, ok := expected[key]
			if !ok {
				entry = &expectations{matches: map[string]bool{}}
				expected[key] = entry
				order = append(order, key)
			}
			values := strings.SplitN(right, " / ", 2)
			value, ok := decodeJSONString(t, values[0])
			entry.decode, entry.hasDecode = value, ok
			kittyValue, kittyOK := decodeJSONString(t, values[1])
			entry.kittyDecode, entry.hasKittyDec = kittyValue, kittyOK

		case "match":
			data, _ := decodeJSONString(t, dataLiteral)
			keyID := extra
			key := keyOf(kittyActive, data)
			entry, ok := expected[key]
			if !ok {
				entry = &expectations{matches: map[string]bool{}}
				expected[key] = entry
				order = append(order, key)
			}
			entry.matches[keyID] = true

		default:
			t.Fatalf("unknown golden command %q", command)
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan golden: %v", err)
	}

	// Rebuild the data list in upstream order for readable failures.
	dataOf := func(key string) (bool, string) {
		parts := strings.SplitN(key, "\x00", 2)
		return parts[0] == "true", parts[1]
	}

	for _, key := range order {
		kitty, data := dataOf(key)
		entry := expected[key]
		SetKittyProtocolActive(kitty)
		t.Cleanup(func() { SetKittyProtocolActive(false) })

		if got, ok := ParseKey(data); got != entry.parseKey || ok != entry.hasParseKey {
			t.Fatalf("kitty=%v ParseKey(%q) = %q,%v want %q,%v",
				kitty, data, got, ok, entry.parseKey, entry.hasParseKey)
		}

		if got, ok := DecodePrintableKey(data); got != entry.decode || ok != entry.hasDecode {
			t.Fatalf("kitty=%v DecodePrintableKey(%q) = %q,%v want %q,%v",
				kitty, data, got, ok, entry.decode, entry.hasDecode)
		}
		if got, ok := DecodeKittyPrintable(data); got != entry.kittyDecode || ok != entry.hasKittyDec {
			t.Fatalf("kitty=%v DecodeKittyPrintable(%q) = %q,%v want %q,%v",
				kitty, data, got, ok, entry.kittyDecode, entry.hasKittyDec)
		}

		for _, keyID := range goldenKeyIDs {
			want := entry.matches[keyID]
			if got := MatchesKey(data, keyID); got != want {
				t.Fatalf("kitty=%v MatchesKey(%q, %q) = %v want %v", kitty, data, keyID, got, want)
			}
		}
	}
}

// splitGoldenLeft splits a golden left-hand side into the command, the JSON
// string literal (which may contain spaces), and any trailing key id.
func splitGoldenLeft(left string) (command string, dataLiteral string, extra string) {
	space := strings.IndexByte(left, ' ')
	if space == -1 {
		return left, "", ""
	}
	command = left[:space]
	rest := left[space+1:]
	if !strings.HasPrefix(rest, "\"") {
		return command, rest, ""
	}
	index := 1
	for index < len(rest) {
		if rest[index] == '\\' {
			index += 2
			continue
		}
		if rest[index] == '"' {
			break
		}
		index++
	}
	if index >= len(rest) {
		return command, rest, ""
	}
	return command, rest[:index+1], strings.TrimSpace(rest[index+1:])
}

func keyOf(kittyActive bool, data string) string {
	if kittyActive {
		return "true\x00" + data
	}
	return "false\x00" + data
}

// TestMatchesRawBackspaceWindowsTerminal covers the env-dependent heuristic
// that is not part of the golden matrix (generated without WT_SESSION).
func TestMatchesRawBackspaceWindowsTerminal(t *testing.T) {
	SetKittyProtocolActive(false)
	t.Cleanup(func() { SetKittyProtocolActive(false) })

	// Outside Windows Terminal, raw 0x08 is plain backspace.
	if !MatchesKey("\x08", "backspace") {
		t.Fatal("0x08 must be backspace without WT_SESSION")
	}
	if MatchesKey("\x08", "ctrl+backspace") {
		t.Fatal("0x08 must not be ctrl+backspace without WT_SESSION")
	}
	if key, ok := ParseKey("\x08"); !ok || key != "backspace" {
		t.Fatalf("ParseKey = %q,%v", key, ok)
	}

	// Windows Terminal uses raw 0x08 for Ctrl+Backspace. The SSH guards must
	// be cleared so the simulation is hermetic.
	t.Setenv("WT_SESSION", "abc")
	t.Setenv("SSH_CONNECTION", "")
	t.Setenv("SSH_CLIENT", "")
	t.Setenv("SSH_TTY", "")
	if MatchesKey("\x08", "backspace") {
		t.Fatal("0x08 must not be backspace with WT_SESSION")
	}
	if !MatchesKey("\x08", "ctrl+backspace") {
		t.Fatal("0x08 must be ctrl+backspace with WT_SESSION")
	}
	if key, ok := ParseKey("\x08"); !ok || key != "ctrl+backspace" {
		t.Fatalf("ParseKey = %q,%v", key, ok)
	}

	// 0x7f is always backspace.
	if !MatchesKey("\x7f", "backspace") || !isWindowsTerminalSession() {
		t.Fatal("0x7f handling changed")
	}

	// An SSH session disables the Windows Terminal heuristic.
	t.Setenv("SSH_CONNECTION", "1 2 3 4")
	if isWindowsTerminalSession() {
		t.Fatal("SSH_CONNECTION must disable the heuristic")
	}
	if !MatchesKey("\x08", "backspace") {
		t.Fatal("0x08 must be backspace over SSH")
	}
}

// TestDecodePrintableKeyModifiers covers the modifier filtering that the
// golden matrix does not reach.
func TestDecodePrintableKeyModifiers(t *testing.T) {
	// Super (8) plus plain (1-indexed 9) is rejected: only shift and lock
	// modifiers are allowed.
	if got, ok := DecodeKittyPrintable("\x1b[97;9u"); ok {
		t.Fatalf("super modifier accepted: %q", got)
	}
	// Shift is accepted and prefers the shifted key.
	if got, ok := DecodeKittyPrintable("\x1b[97:65;2u"); !ok || got != "A" {
		t.Fatalf("shifted key = %q,%v", got, ok)
	}
	// Lock bits (Num/Caps Lock, 64+128) are masked out.
	if got, ok := DecodeKittyPrintable("\x1b[97;193u"); !ok || got != "a" {
		t.Fatalf("lock modifiers = %q,%v", got, ok)
	}
	// Control characters are dropped.
	if got, ok := DecodeKittyPrintable("\x1b[13u"); ok {
		t.Fatalf("control codepoint accepted: %q", got)
	}
	// Unsupported modifier bits make ParseKey give up.
	if key, ok := ParseKey("\x1b[97;257u"); ok {
		t.Fatalf("unsupported modifier parsed: %q", key)
	}
	// A surrogate codepoint is not a valid character.
	if got, ok := DecodeKittyPrintable("\x1b[55296u"); ok {
		t.Fatalf("surrogate accepted: %q", got)
	}
}

// TestParseKeyKittyPrintablePassthrough verifies plain CSI-u printable input.
func TestParseKeyKittyPrintablePassthrough(t *testing.T) {
	SetKittyProtocolActive(true)
	t.Cleanup(func() { SetKittyProtocolActive(false) })

	if key, ok := ParseKey("\x1b[97u"); !ok || key != "a" {
		t.Fatalf("plain CSI-u = %q,%v", key, ok)
	}
	if key, ok := ParseKey("\x1b[97;1:3u"); !ok || key != "a" {
		t.Fatalf("release CSI-u = %q,%v", key, ok)
	}
	if got := LastKeyEventType(); got != KeyEventRelease {
		t.Fatalf("last event type = %q", got)
	}
	if key, ok := ParseKey("\x1b[1089::99;5u"); !ok || key != "ctrl+c" {
		t.Fatalf("base layout = %q,%v", key, ok)
	}
}
