package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream renderLatex with Node
// for both inline and display modes. See tui/testdata/latex_golden.txt.

func loadLatexGolden(t *testing.T) map[string]*string {
	t.Helper()
	file, err := os.Open("testdata/latex_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]*string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		label := strings.TrimPrefix(parts[0], "latex ")
		if parts[1] == "null" {
			values[label] = nil
			continue
		}
		var value string
		if err := json.Unmarshal([]byte(parts[1]), &value); err != nil {
			t.Fatalf("bad golden value %q: %v", line, err)
		}
		values[label] = &value
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func loadLatexCorpus(t *testing.T) map[string]string {
	t.Helper()
	data, err := os.ReadFile("testdata/latex_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	raw := map[string]struct {
		Text string `json:"text"`
	}{}
	if err := json.Unmarshal(data, &raw); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	corpus := map[string]string{}
	for label, spec := range raw {
		corpus[label] = spec.Text
	}
	return corpus
}

// TestLatexAgainstUpstreamGolden compares the LaTeX renderer with upstream for
// both inline and display modes.
func TestLatexAgainstUpstreamGolden(t *testing.T) {
	golden := loadLatexGolden(t)
	corpus := loadLatexCorpus(t)

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		source := corpus[label]
		for _, display := range []bool{false, true} {
			key := label
			if display {
				key += "@display"
			}
			want, ok := golden[key]
			if !ok {
				t.Fatalf("missing golden %q", key)
			}
			got, gotOK := RenderLatex(source, RenderLatexOptions{Display: display})
			if want == nil {
				if gotOK {
					t.Fatalf("%s: expected unsupported, got %q", key, got)
				}
				continue
			}
			if !gotOK {
				t.Fatalf("%s: unexpectedly unsupported", key)
			}
			if got != *want {
				t.Fatalf("%s:\n got %q\nwant %q", key, got, *want)
			}
		}
	}
}
