package tui

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream layout.ts with Node:
// renderLayoutFrame outputs, child rects, scroll state, scrollbar geometry,
// and hit-test paths. See tui/testdata/layoutframe_golden.txt.

// probeComponent mimics the upstream probe component: lines are padded or cut
// by rune count (the JS probe used string length).
type probeComponent struct {
	lines []string
}

func (p *probeComponent) Render(width int) []string {
	out := make([]string, 0, len(p.lines))
	for _, line := range p.lines {
		runes := []rune(line)
		if len(runes) >= width {
			out = append(out, string(runes[:width]))
		} else {
			out = append(out, line+strings.Repeat(" ", width-len(runes)))
		}
	}
	return out
}

func (p *probeComponent) Invalidate() {}

func probe(lines ...string) Component { return &probeComponent{lines: lines} }

type layoutFrameGolden struct {
	values map[string]string
}

func loadLayoutFrameGolden(t *testing.T) *layoutFrameGolden {
	t.Helper()
	file, err := os.Open("testdata/layoutframe_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return &layoutFrameGolden{values: values}
}

func (g *layoutFrameGolden) check(t *testing.T, label string, got any) {
	t.Helper()
	want, ok := g.values[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	rendered := renderGoldenValue(got)
	if rendered != want {
		t.Fatalf("%s:\n got %s\nwant %s", label, rendered, want)
	}
}

// renderGoldenValue formats a value the way the probe script printed it.
func renderGoldenValue(value any) string {
	switch typed := value.(type) {
	case string:
		return typed
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", typed)
	default:
		return mustJSON(value)
	}
}

type goldenRect struct {
	X int `json:"x"`
	Y int `json:"y"`
	W int `json:"w"`
	H int `json:"h"`
}

// TestLayoutFrameAgainstUpstreamGolden replays the upstream layout probe.
func TestLayoutFrameAgainstUpstreamGolden(t *testing.T) {
	golden := loadLayoutFrameGolden(t)

	frame := func(label string, root Component, width int, height int) LayoutFrame {
		frame := RenderLayoutFrame(root, width, height, func() {})
		golden.check(t, "frame "+label, frame.Lines)
		rects := make([]goldenRect, 0, len(frame.Root.Children))
		for _, child := range frame.Root.Children {
			rects = append(rects, goldenRect{X: child.Rect.X, Y: child.Rect.Y, W: child.Rect.Width, H: child.Rect.Height})
		}
		golden.check(t, "boxes "+label, rects)
		return frame
	}

	// 1. Plain leaf.
	frame("leaf", probe("abc"), 5, 3)
	// 2. VStack filling the frame.
	frame("vstack", NewVStack([]Component{probe("aa"), probe("bb"), probe("cc")}, StackOptions{}), 4, 6)
	// 3. VStack with a gap.
	gapOne := intPtrValue(1)
	frame("vstack-gap", NewVStack([]Component{probe("aa"), probe("bb")}, StackOptions{Gap: gapOne}), 4, 5)
	// 4. HStack filling the frame.
	frame("hstack", NewHStack([]Component{probe("ab"), probe("cd")}, StackOptions{}), 6, 2)
	// 5. Text in a frame.
	frame("text", NewText("hello world", 1, 0, nil), 8, 4)
	// 6. A leaf taller than the frame.
	frame("clamp", probe("1", "2", "3", "4"), 3, 2)
	// 7. A cursor marker beyond the allocated height sets the line offset.
	frame("cursor", probe("x"+CursorMarker+"y"), 4, 1)

	// Scroll view cases.
	tall := probe("L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8")
	scrollFollow := NewScrollView(tall, ScrollViewOptions{Follow: "end", Primary: true})
	followFrame := frame("scroll-follow-end", scrollFollow, 6, 3)
	golden.check(t, "scrollTop scroll-follow-end",
		fmt.Sprintf("%d following=%v viewport=%d", scrollFollow.ScrollTop(), scrollFollow.IsFollowingEnd(), scrollFollow.ViewportHeight()))
	golden.check(t, "primary scroll-follow-end", followFrame.PrimaryScrollView == scrollFollow)

	scrollAlways := NewScrollView(tall, ScrollViewOptions{Scrollbar: ScrollbarAlways})
	frame("scroll-always", scrollAlways, 6, 3)
	golden.check(t, "scrollTop scroll-always", fmt.Sprintf("%d", scrollAlways.ScrollTop()))
	scrollAlways.ScrollTo(3)
	alwaysScrolled := RenderLayoutFrame(scrollAlways, 6, 3, func() {})
	golden.check(t, "frame scroll-always-scrolled", alwaysScrolled.Lines)
	geometry, ok := GetScrollbarGeometry(alwaysScrolled.Root, false)
	golden.check(t, "geometry scroll-always", goldenGeometry(geometry, ok))
	hiddenGeometry, hiddenOK := GetScrollbarGeometry(alwaysScrolled.Root, true)
	golden.check(t, "geometry-hidden scroll-always", goldenGeometry(hiddenGeometry, hiddenOK))

	scrollAuto := NewScrollView(tall, ScrollViewOptions{Scrollbar: ScrollbarAuto})
	RenderLayoutFrame(scrollAuto, 6, 3, func() {})
	scrollAuto.SetScrollbarActive(true)
	autoActive := RenderLayoutFrame(scrollAuto, 6, 3, func() {})
	golden.check(t, "frame scroll-auto-active", autoActive.Lines)
	golden.check(t, "auto visible", fmt.Sprintf("visible=%v active=%v", scrollAuto.IsScrollbarVisible(), scrollAuto.IsScrollbarActive()))

	scrollAuto.ScrollBy(2)
	consumed := scrollAuto.ScrollBy(100)
	golden.check(t, "scrollBy2", fmt.Sprintf("%d consumed=%d scrollTopAfter=%d", 2, consumed, scrollAuto.ScrollTop()))

	// Nested: a VStack with a scroll view and a footer.
	scrollNested := NewScrollView(probe("A", "B", "C", "D", "E", "F"), ScrollViewOptions{})
	nested := NewVStack([]Component{scrollNested, probe("footer")}, StackOptions{})
	nestedFrame := frame("nested", nested, 8, 5)
	golden.check(t, "primary nested", nestedFrame.PrimaryScrollView == scrollNested)

	// Hit testing.
	hitFrame := RenderLayoutFrame(NewVStack([]Component{probe("top"), probe("mid"), probe("bot")}, StackOptions{}), 4, 3, func() {})
	golden.check(t, "boxesAt 0,0", hitYs(GetLayoutBoxesAt(hitFrame, 0, 0)))
	golden.check(t, "boxesAt 0,2", hitYs(GetLayoutBoxesAt(hitFrame, 0, 2)))
	golden.check(t, "boxesAt 0,9", len(GetLayoutBoxesAt(hitFrame, 0, 9)))
	scrollFrame := RenderLayoutFrame(NewVStack([]Component{
		NewScrollView(probe("1", "2", "3", "4"), ScrollViewOptions{}), probe("f"),
	}, StackOptions{}), 4, 4, func() {})
	golden.check(t, "scrollViewsAt 0,0", len(GetScrollViewsAt(scrollFrame, 0, 0)))
	_, found := GetScrollViewBox(scrollFrame, scrollFrame.Root.Children[0].ScrollView)
	golden.check(t, "scrollViewBox", found)

	// Scroll position behaviour.
	behaviour := NewScrollView(probe("1", "2", "3", "4", "5"), ScrollViewOptions{Follow: "end"})
	RenderLayoutFrame(behaviour, 4, 2, func() {})
	golden.check(t, "follow scrollTop", fmt.Sprintf("%d following=%v", behaviour.ScrollTop(), behaviour.IsFollowingEnd()))
	behaviour.ScrollToStart()
	golden.check(t, "after start", fmt.Sprintf("%d following=%v", behaviour.ScrollTop(), behaviour.IsFollowingEnd()))
	behaviour.ScrollTo(1)
	golden.check(t, "after to1", fmt.Sprintf("%d following=%v", behaviour.ScrollTop(), behaviour.IsFollowingEnd()))
	behaviour.ScrollToEnd()
	golden.check(t, "after end", fmt.Sprintf("%d following=%v", behaviour.ScrollTop(), behaviour.IsFollowingEnd()))
	behaviour.ScrollTo(3, ScrollToRequest{DisableFollow: true})
	golden.check(t, "after disableFollow", fmt.Sprintf("%d following=%v", behaviour.ScrollTop(), behaviour.IsFollowingEnd()))
	behaviour.ScrollBy(-2)
	consumed2 := behaviour.ScrollBy(-100)
	golden.check(t, "after by-2", fmt.Sprintf("%d following=%v consumed=%d top=%d",
		1, false, consumed2, behaviour.ScrollTop()))
}

func hitYs(boxes []*LayoutBox) []int {
	out := make([]int, 0, len(boxes))
	for _, box := range boxes {
		out = append(out, box.Rect.Y)
	}
	return out
}

func goldenGeometry(geometry ScrollbarGeometry, ok bool) string {
	if !ok {
		return "undefined"
	}
	return fmt.Sprintf(`{"column":%d,"trackTop":%d,"trackHeight":%d,"thumbTop":%d,"thumbHeight":%d,"maxScrollTop":%d}`,
		geometry.Column, geometry.TrackTop, geometry.TrackHeight, geometry.ThumbTop, geometry.ThumbHeight, geometry.MaxScrollTop)
}

// TestScrollViewRendering covers behaviours the probe cannot express (the
// render width padding and the scrollbar reservation).
func TestScrollViewRendering(t *testing.T) {
	child := probe("abc")
	view := NewScrollView(child, ScrollViewOptions{Scrollbar: ScrollbarAlways})
	if got := view.GetContentWidth(10); got != 9 {
		t.Fatalf("content width = %d", got)
	}
	lines := view.Render(10)
	if len(lines) != 1 || lines[0] != "abc       " || VisibleWidth(lines[0]) != 10 {
		t.Fatalf("render = %q", lines)
	}
	if view.Child() != child {
		t.Fatal("child mismatch")
	}
	// Without the scrollbar the content uses the full width.
	plain := NewScrollView(probe("abc"), ScrollViewOptions{})
	if got := plain.GetContentWidth(10); got != 10 {
		t.Fatalf("content width = %d", got)
	}
	if lines := plain.Render(4); len(lines) != 1 || lines[0] != "abc " {
		t.Fatalf("render = %q", lines)
	}

	// The single-child invariants panic like upstream's throws.
	assertPanics(t, "AddChild", func() { view.AddChild(probe("x")) })
	assertPanics(t, "RemoveChild", func() { view.RemoveChild(child) })
	assertPanics(t, "Clear", func() { view.Clear() })
	assertPanics(t, "axis", func() { NewScrollView(probe("x"), ScrollViewOptions{Axis: "horizontal"}) })
}

func assertPanics(t *testing.T, label string, fn func()) {
	t.Helper()
	defer func() {
		if recover() == nil {
			t.Fatalf("%s must panic", label)
		}
	}()
	fn()
}

// TestScrollbarVisibility verifies the hidden/auto/always modes.
func TestScrollbarVisibility(t *testing.T) {
	tall := probe("1", "2", "3", "4", "5", "6")

	hidden := NewScrollView(tall, ScrollViewOptions{})
	RenderLayoutFrame(hidden, 4, 3, func() {})
	if hidden.IsScrollbarVisible() {
		t.Fatal("hidden scrollbar visible")
	}

	auto := NewScrollView(tall, ScrollViewOptions{Scrollbar: ScrollbarAuto})
	RenderLayoutFrame(auto, 4, 3, func() {})
	if auto.IsScrollbarVisible() {
		t.Fatal("auto scrollbar visible before activity")
	}
	auto.ScrollBy(1)
	if !auto.IsScrollbarVisible() {
		t.Fatal("auto scrollbar hidden after activity")
	}

	always := NewScrollView(tall, ScrollViewOptions{Scrollbar: ScrollbarAlways})
	RenderLayoutFrame(always, 4, 3, func() {})
	if !always.IsScrollbarVisible() {
		t.Fatal("always scrollbar hidden")
	}
	always.SetScrollbar(ScrollbarHidden)
	if always.IsScrollbarVisible() {
		t.Fatal("scrollbar still visible after mode change")
	}

	// A short child never shows an auto scrollbar.
	short := NewScrollView(probe("1"), ScrollViewOptions{Scrollbar: ScrollbarAuto})
	RenderLayoutFrame(short, 4, 3, func() {})
	short.ScrollBy(1)
	if short.IsScrollbarVisible() {
		t.Fatal("short content must not scroll")
	}
}
