package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by lexing tui/testdata/md_corpus.json with the
// upstream Marked configuration (strict strikethrough + LaTeX extensions) and
// projecting the tokens the way projectMdToken does.

var mdRawTypes = map[string]bool{"code": true, "latex": true, "latexBlock": true, "escape": true}

// projectMdToken normalizes a token for comparison with the upstream probe.
func projectMdToken(token *MdToken) map[string]any {
	projected := map[string]any{}
	if token.Type != "" {
		projected["type"] = token.Type
	}
	if mdRawTypes[token.Type] && token.Raw != "" {
		projected["raw"] = token.Raw
	}
	if token.Text != "" {
		projected["text"] = token.Text
	}
	if token.Depth != 0 {
		projected["depth"] = token.Depth
	}
	if token.Ordered {
		projected["ordered"] = true
		projected["start"] = token.Start
	}
	if token.Href != "" {
		projected["href"] = token.Href
	}
	if token.Title != "" {
		projected["title"] = token.Title
	}
	if token.Lang != "" {
		projected["lang"] = token.Lang
	}
	if token.HasCellAlign {
		projected["align"] = token.CellAlign
	}
	if len(token.Align) > 0 {
		aligns := make([]any, 0, len(token.Align))
		for _, align := range token.Align {
			if align == "" {
				aligns = append(aligns, nil)
			} else {
				aligns = append(aligns, align)
			}
		}
		projected["align"] = aligns
	}
	if token.Task {
		projected["task"] = true
		projected["checked"] = token.Checked
	}
	if token.Pending {
		projected["pending"] = true
	}
	if len(token.Items) > 0 {
		projected["items"] = projectMdTokens(token.Items)
	}
	if len(token.Tokens) > 0 {
		projected["tokens"] = projectMdTokens(token.Tokens)
	}
	if len(token.Header) > 0 {
		projected["header"] = projectMdTokens(token.Header)
	}
	if len(token.Rows) > 0 {
		rows := make([]any, 0, len(token.Rows))
		for _, row := range token.Rows {
			rows = append(rows, projectMdTokens(row))
		}
		projected["rows"] = rows
	}
	return projected
}

func projectMdTokens(tokens []*MdToken) []any {
	out := make([]any, 0, len(tokens))
	for _, token := range tokens {
		out = append(out, projectMdToken(token))
	}
	return out
}

// stableMDValue serializes with sorted keys, matching the JS stable() helper.
func stableMDValue(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case string:
		return mustJSON(typed)
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case int:
		return itoa(typed)
	case []any:
		parts := make([]string, 0, len(typed))
		for _, item := range typed {
			parts = append(parts, stableMDValue(item))
		}
		return "[" + strings.Join(parts, ",") + "]"
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sortStrings(keys)
		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			parts = append(parts, mustJSON(key)+":"+stableMDValue(typed[key]))
		}
		return "{" + strings.Join(parts, ",") + "}"
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			panic(err)
		}
		return string(encoded)
	}
}

func loadMDCorpus(t *testing.T) map[string]string {
	t.Helper()
	data, err := os.ReadFile("testdata/md_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]string{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	return corpus
}

func loadMDGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/md_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

// TestMarkdownParserAgainstUpstreamGolden compares the Go lexer with upstream
// Marked for the corpus.
func TestMarkdownParserAgainstUpstreamGolden(t *testing.T) {
	corpus := loadMDCorpus(t)
	golden := loadMDGolden(t)

	names := make([]string, 0, len(corpus))
	for name := range corpus {
		names = append(names, name)
	}
	sortStrings(names)

	for _, name := range names {
		want, ok := golden[name]
		if !ok {
			t.Fatalf("missing golden %q", name)
		}
		tokens := LexMarkdown(corpus[name])
		TrimPartialClosingFences(tokens)
		got := stableMDValue(projectMdTokens(tokens))
		if got != want {
			t.Fatalf("%s:\n got %s\nwant %s", name, got, want)
		}
	}
}

// TestTrimPartialClosingFences verifies the streamed-fence trimming.
func TestTrimPartialClosingFences(t *testing.T) {
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{"partial backticks", "```js\ncode();\n``", "code();"},
		{"partial newline", "```js\ncode();\n``\n", "code();\n``"},
		{"complete fence", "```js\ncode();\n```", "code();"},
		{"tilde fence", "~~~\ncode\n~", "code"},
		{"not a fence", "text\n``", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			tokens := LexMarkdown(tc.input)
			TrimPartialClosingFences(tokens)
			if len(tokens) != 1 {
				t.Fatalf("tokens = %+v", tokens)
			}
			if tc.name == "not a fence" {
				// A paragraph with a stray partial fence is untouched.
				if tokens[0].Type != "paragraph" || tokens[0].Text != tc.input {
					t.Fatalf("tokens = %+v", tokens[0])
				}
				return
			}
			if tokens[0].Type != "code" || tokens[0].Text != tc.want {
				t.Fatalf("token = %+v, want text %q", tokens[0], tc.want)
			}
		})
	}

	// The trim recurses into the last nested list item and blockquote.
	nested := LexMarkdown("- a\n\n  ```\n  x\n  `")
	TrimPartialClosingFences(nested)
	item := nested[len(nested)-1]
	if item.Type != "list" {
		t.Fatalf("tokens = %+v", nested)
	}
	lastItem := item.Items[len(item.Items)-1]
	code := lastItem.Tokens[len(lastItem.Tokens)-1]
	if code.Type != "code" || code.Text != "x" {
		t.Fatalf("nested code = %+v", code)
	}

	quoted := LexMarkdown("> ```\n> x\n> `")
	TrimPartialClosingFences(quoted)
	quote := quoted[len(quoted)-1]
	if quote.Type != "blockquote" || quote.Tokens[0].Text != "x" {
		t.Fatalf("quote = %+v", quote)
	}
}
