package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by rendering the corpus in
// tui/testdata/md_render_corpus.json with the upstream Markdown component and
// a tagging theme. LaTeX is excluded until the latex.ts port lands (D68).

func loadMDRenderGolden(t *testing.T) map[string][]string {
	t.Helper()
	file, err := os.Open("testdata/md_render_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string][]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		label := strings.TrimPrefix(parts[0], "md ")
		var lines []string
		if err := json.Unmarshal([]byte(parts[1]), &lines); err != nil {
			t.Fatalf("bad golden render %q: %v", line, err)
		}
		values[label] = lines
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func mdTag(name string) func(string) string {
	return func(text string) string { return "<" + name + ">" + text + "</" + name + ">" }
}

func mdTestTheme() MarkdownTheme {
	return MarkdownTheme{
		Heading:         mdTag("h"),
		Link:            mdTag("link"),
		LinkURL:         mdTag("url"),
		Code:            mdTag("code"),
		CodeBlock:       mdTag("cb"),
		CodeBlockBorder: mdTag("cbb"),
		Quote:           mdTag("q"),
		QuoteBorder:     mdTag("qb"),
		Hr:              mdTag("hr"),
		ListBullet:      mdTag("lb"),
		Bold:            mdTag("b"),
		Italic:          mdTag("i"),
		Strikethrough:   mdTag("s"),
		Underline:       mdTag("u"),
	}
}

type mdRenderCase struct {
	label        string
	text         string
	widths       []int
	paddingX     int
	paddingY     int
	defaultStyle *DefaultTextStyle
	options      MarkdownOptions
}

// TestMarkdownAgainstUpstreamGolden replays the upstream render corpus.
func TestMarkdownAgainstUpstreamGolden(t *testing.T) {
	golden := loadMDRenderGolden(t)
	theme := mdTestTheme()

	cases := []mdRenderCase{
		{label: "para", text: "Hello world", widths: []int{20, 5}},
		{label: "para-spacing", text: "one\n\ntwo", widths: []int{20}},
		{label: "headings", text: "# H1\n\n## H2\n\n### H3\n\n#### H4", widths: []int{24}},
		{label: "headings-inline", text: "# A **b** and `c`", widths: []int{30}},
		{label: "emphasis", text: "a *em* and **strong** and ~~del~~ and `code`", widths: []int{40}},
		{label: "fence", text: "```js\nconst x = 1;\n```", widths: []int{30}},
		{label: "fence-long", text: "```python\ndef f(x):\n    return x + 1\n```", widths: []int{20}},
		{label: "indented-code", text: "    indented code", widths: []int{20}},
		{label: "ul", text: "- a\n- b\n- c", widths: []int{20}},
		{label: "ul-nested", text: "- a\n  - b\n    - c\n- d", widths: []int{24}},
		{label: "ol", text: "1. one\n2. two", widths: []int{20}},
		{label: "ol-start", text: "5. five\n6. six", widths: []int{20}},
		{label: "task", text: "- [ ] todo\n- [x] done", widths: []int{24}},
		{label: "loose", text: "- a\n\n- b", widths: []int{20}},
		{label: "quote", text: "> quoted text here", widths: []int{20}},
		{label: "quote-multi", text: "> para\n>\n> - a\n> - b", widths: []int{24}},
		{label: "quote-nested", text: "> > deep", widths: []int{20}},
		{label: "quote-spacing", text: "before\n\n> quote\n\nafter", widths: []int{24}},
		{label: "hr", text: "a\n\n---\n\nb", widths: []int{10}},
		{label: "table", text: "| a | b |\n| - | - |\n| 1 | 2 |\n| 3 | 4 |", widths: []int{30, 20}},
		{label: "table-align", text: "| left | center | right |\n| :- | :-: | -: |\n| a | b | c |", widths: []int{40}},
		{label: "table-wrap", text: "| col |\n| - |\n| a very long cell value here |", widths: []int{20}},
		{label: "table-narrow", text: "| a | b | c |\n| - | - | - |\n| 1 | 2 | 3 |", widths: []int{8}},
		{label: "table-inline", text: "| **b** | `c` |\n| - | - |\n| [l](u) | x |", widths: []int{30}},
		{label: "links", text: "[text](http://x) and [http://y](http://y) and <http://z>", widths: []int{40}},
		{label: "image", text: "![alt](img.png)", widths: []int{20}},
		{label: "html", text: "<div>\nraw\n</div>", widths: []int{20}},
		{label: "inline-html", text: "text <b>bold</b> text", widths: []int{30}},
		{label: "escapes", text: "a \\* b \\_ c", widths: []int{20}},
		{label: "br", text: "line one  \nline two", widths: []int{20}},
		{label: "mixed", text: "# Title\n\npara **b**\n\n- item one\n- item two\n\n> quote\n\n```py\nx=1\n```\n\n| a |\n| - |\n| 1 |", widths: []int{30}},
		{label: "padding", text: "text", widths: []int{20}, paddingX: 2, paddingY: 1},
		// JSON drops functions, so the colour/background style is exercised by
		// this case and the transform by the next one.
		{label: "default-style", text: "plain **bold** text", widths: []int{24},
			defaultStyle: &DefaultTextStyle{Bold: true}},
		{label: "default-style-full", text: "plain **bold** text", widths: []int{24},
			defaultStyle: &DefaultTextStyle{
				Color:   func(text string) string { return "<col>" + text + "</col>" },
				BgColor: func(text string) string { return "<bg>" + text + "</bg>" },
				Bold:    true,
				Italic:  true,
			}},
		{label: "transform", text: "abc", widths: []int{20}},
		{label: "transform-upper", text: "abc", widths: []int{20}, options: MarkdownOptions{
			Transform: func(markdown string, availableWidth int) string { return strings.ToUpper(markdown) },
		}},
		{label: "preserve-markers", text: "- a\n1. b", widths: []int{20}, options: MarkdownOptions{PreserveOrderedListMarkers: true}},
		{label: "preserve-escapes", text: "a \\* b", widths: []int{20}, options: MarkdownOptions{PreserveBackslashEscapes: true}},
		{label: "no-latex", text: "math $x$ here", widths: []int{20}, options: MarkdownOptions{RenderLatex: boolPtr(false)}},
	}

	for _, tc := range cases {
		markdown := NewMarkdown(tc.text, tc.paddingX, tc.paddingY, theme, tc.defaultStyle, tc.options)
		for _, width := range tc.widths {
			label := tc.label + "@" + itoa(width)
			want, ok := golden[label]
			if !ok {
				t.Fatalf("missing golden %q", label)
			}
			got := markdown.Render(width)
			if len(got) != len(want) {
				t.Fatalf("%s:\n got %q\nwant %q", label, got, want)
			}
			for index := range got {
				if got[index] != want[index] {
					t.Fatalf("%s line %d:\n got %q\nwant %q", label, index, got[index], want[index])
				}
			}
		}
	}
}

func boolPtr(value bool) *bool { return &value }

// TestMarkdownLatexAgainstUpstreamGolden verifies the LaTeX path inside the
// markdown renderer (upstream renders "math $x^2$ here" as "math x² here").
func TestMarkdownLatexAgainstUpstreamGolden(t *testing.T) {
	golden := loadMDRenderGolden(t)
	want, ok := golden["latex-fallback@20"]
	if !ok {
		t.Fatal("missing latex golden")
	}
	markdown := NewMarkdown("math $x^2$ here", 0, 0, mdTestTheme(), nil, MarkdownOptions{})
	got := markdown.Render(20)
	if len(got) != len(want) || got[0] != want[0] {
		t.Fatalf("got %q want %q", got, want)
	}
}

// TestMarkdownCacheAndLatexFallback covers the cache and the pending LaTeX
// renderer fallback (D68).
func TestMarkdownCacheAndLatexFallback(t *testing.T) {
	markdown := NewMarkdown("cache me", 0, 0, mdTestTheme(), nil, MarkdownOptions{})
	first := markdown.Render(20)
	second := markdown.Render(20)
	if len(first) != len(second) || first[0] != second[0] {
		t.Fatal("cache mismatch")
	}
	markdown.SetText("other")
	if got := markdown.Render(20); len(got) != 1 || !strings.HasPrefix(got[0], "other") {
		t.Fatalf("render after setText = %q", got)
	}
	markdown.Invalidate()
	if got := markdown.Render(0); len(got) == 0 {
		t.Fatal("empty width render failed")
	}
	empty := NewMarkdown("", 0, 0, mdTestTheme(), nil, MarkdownOptions{})
	if got := empty.Render(10); len(got) != 0 {
		t.Fatalf("empty render = %q", got)
	}
	blank := NewMarkdown("   \n  ", 0, 0, mdTestTheme(), nil, MarkdownOptions{})
	if got := blank.Render(10); len(got) != 0 {
		t.Fatalf("blank render = %q", got)
	}
	// The latex renderer is ported (D68 closed): x^2 renders as x².
	if got, ok := RenderLatex("x^2", RenderLatexOptions{Display: false}); !ok || got != "x²" {
		t.Fatalf("RenderLatex = %q,%v", got, ok)
	}
	// Unsupported syntax still reports unsupported so the renderer falls back
	// to the raw source.
	if _, ok := RenderLatex("\\foo{x}", RenderLatexOptions{Display: false}); ok {
		t.Fatal("unknown command must be unsupported")
	}
}
