package tui

import (
	"bufio"
	"os"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// The golden file is generated by running the upstream SelectList,
// TruncatedText, Loader, and AltScreenFlashContainer with Node. See
// tui/testdata/select_golden.txt.

func loadSelectGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/select_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func identityFunc(text string) string { return text }

func tagFunc(name string) func(string) string {
	return func(text string) string { return "<" + name + ">" + text + "</" + name + ">" }
}

func plainSelectTheme() SelectListTheme {
	return SelectListTheme{
		SelectedPrefix: identityFunc,
		SelectedText:   identityFunc,
		Description:    identityFunc,
		ScrollInfo:     identityFunc,
		NoMatch:        identityFunc,
	}
}

func selectItems() []SelectItem {
	return []SelectItem{
		{Value: "alpha", Label: "alpha", Description: "The first letter"},
		{Value: "beta", Label: "beta"},
		{Value: "gamma", Label: "gamma", Description: "Third\nletter"},
		{Value: "delta", Label: "a-very-long-label-that-needs-truncation", Description: "Fourth"},
		{Value: "epsilon", Label: "epsilon", Description: "Fifth"},
		{Value: "zeta", Label: "zeta"},
		{Value: "eta", Label: "eta", Description: "Seventh"},
	}
}

// TestSelectListAgainstUpstreamGolden verifies the list rendering and
// selection behaviour.
func TestSelectListAgainstUpstreamGolden(t *testing.T) {
	golden := loadSelectGolden(t)
	theme := plainSelectTheme()

	basic := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	checkInputGolden(t, golden, "select basic", basic.Render(60))
	checkInputGolden(t, golden, "select narrow", basic.Render(20))
	checkInputGolden(t, golden, "select exactly-41", basic.Render(41))

	scrolled := NewSelectList(selectItems(), 3, theme, SelectListLayoutOptions{})
	scrolled.HandleInput("\x1b[B")
	checkInputGolden(t, golden, "select scrolled", scrolled.Render(60))

	filtered := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	filtered.SetFilter("ga")
	checkInputGolden(t, golden, "select filtered", filtered.Render(60))

	noMatch := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	noMatch.SetFilter("nope")
	checkInputGolden(t, golden, "select nomatch", noMatch.Render(60))

	tagged := NewSelectList(selectItems(), 5, SelectListTheme{
		SelectedPrefix: tagFunc("p"),
		SelectedText:   tagFunc("s"),
		Description:    tagFunc("d"),
		ScrollInfo:     tagFunc("i"),
		NoMatch:        tagFunc("n"),
	}, SelectListLayoutOptions{})
	checkInputGolden(t, golden, "select tagged", tagged.Render(60))
	checkInputGolden(t, golden, "select tagged-narrow", tagged.Render(30))

	bounds := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{
		MinPrimaryColumnWidth: 4, HasMin: true, MaxPrimaryColumnWidth: 10, HasMax: true,
	})
	checkInputGolden(t, golden, "select bounds", bounds.Render(60))

	custom := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{
		TruncatePrimary: func(context SelectListTruncatePrimaryContext) string {
			if len(context.Text) > 3 {
				return context.Text[:3]
			}
			return context.Text
		},
	})
	checkInputGolden(t, golden, "select custom-truncate", custom.Render(60))

	single := NewSelectList([]SelectItem{{Value: "only", Label: "only"}}, 5, theme, SelectListLayoutOptions{})
	checkInputGolden(t, golden, "select single", single.Render(60))

	scrollInfo := NewSelectList(selectItems(), 2, theme, SelectListLayoutOptions{})
	scrollInfo.SetSelectedIndex(4)
	checkInputGolden(t, golden, "select scroll-info", scrollInfo.Render(60))

	// Selection behaviour.
	selection := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	selection.HandleInput("\x1b[B")
	selection.HandleInput("\x1b[B")
	selected, _ := selection.GetSelectedItem()
	checkInputGolden(t, golden, "selected basic", selected)
	selection.HandleInput("\x1b[A")
	selected, _ = selection.GetSelectedItem()
	checkInputGolden(t, golden, "selected up", selected)
	selection.HandleInput("\x1b[Z")
	selected, _ = selection.GetSelectedItem()
	checkInputGolden(t, golden, "selected after-tab", selected)

	wrapping := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	wrapping.HandleInput("\x1b[A")
	selected, _ = wrapping.GetSelectedItem()
	checkInputGolden(t, golden, "wrap-up", selected.Value)
	for i := 0; i < len(selectItems()); i++ {
		wrapping.HandleInput("\x1b[B")
	}
	selected, _ = wrapping.GetSelectedItem()
	checkInputGolden(t, golden, "wrap-down", selected.Value)

	filterE := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	filterE.SetFilter("e")
	checkInputGolden(t, golden, "filter-e", filterE.Render(60))
}

// TestSelectListCallbacks verifies select/cancel/selection-change and mouse
// handling.
func TestSelectListCallbacks(t *testing.T) {
	theme := plainSelectTheme()
	selected := ""
	cancelled := false
	changes := 0
	list := NewSelectList(selectItems(), 5, theme, SelectListLayoutOptions{})
	list.OnSelect = func(item SelectItem) { selected = item.Value }
	list.OnCancel = func() { cancelled = true }
	list.OnSelectionChange = func(item SelectItem) { changes++ }

	list.HandleInput("\x1b[B")
	if selected != "" || changes != 1 {
		t.Fatalf("selected=%q changes=%d", selected, changes)
	}
	list.HandleInput("\r")
	if selected != "beta" {
		t.Fatalf("selected = %q", selected)
	}
	list.HandleInput("\x1b")
	if !cancelled {
		t.Fatal("cancel not dispatched")
	}

	// Wheel scrolling moves the selection and reports a render.
	previous := list.SelectedIndex()
	result := list.HandleMouse(TuiMouseEvent{Type: MouseWheel, HasWheel: true, WheelDelta: -1, Width: 60, Height: 5})
	if result == nil || !result.Render {
		t.Fatalf("wheel result = %+v", result)
	}
	if list.SelectedIndex() != previous-1 {
		t.Fatalf("index = %d", list.SelectedIndex())
	}
	// Hover does not change the selection.
	before := list.SelectedIndex()
	if got := list.HandleMouse(TuiMouseEvent{Type: MouseMove, Button: MouseButtonLeft, Y: 2, Width: 60, Height: 5}); got != nil {
		t.Fatalf("move = %+v", got)
	}
	if list.SelectedIndex() != before {
		t.Fatal("hover changed the selection")
	}

	// Press focuses and selects; click confirms.
	clicked := ""
	list.OnSelect = func(item SelectItem) { clicked = item.Value }
	press := list.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, Y: 2, Width: 60, Height: 5})
	if press == nil || !press.Focus {
		t.Fatalf("press = %+v", press)
	}
	click := list.HandleMouse(TuiMouseEvent{Type: MouseClick, Button: MouseButtonLeft, Y: 2, Width: 60, Height: 5})
	if click == nil || !click.Handled || clicked == "" {
		t.Fatalf("click = %+v clicked=%q", click, clicked)
	}
	// Out-of-range rows are ignored.
	if got := list.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, Y: 99, Width: 60, Height: 5}); got != nil {
		t.Fatalf("row press = %+v", got)
	}
	// An empty list ignores mouse events.
	empty := NewSelectList(nil, 5, theme, SelectListLayoutOptions{})
	empty.SetFilter("nothing")
	if got := empty.HandleMouse(TuiMouseEvent{Type: MouseWheel, HasWheel: true, WheelDelta: 1}); got != nil {
		t.Fatalf("empty wheel = %+v", got)
	}
}

// TestTruncatedTextAgainstUpstreamGolden verifies the truncated text renders.
func TestTruncatedTextAgainstUpstreamGolden(t *testing.T) {
	golden := loadSelectGolden(t)

	checkInputGolden(t, golden, "truncate plain", NewTruncatedText("hello world", 1, 1).Render(10))
	checkInputGolden(t, golden, "truncate multi", NewTruncatedText("first\nsecond", 0, 0).Render(8))
	checkInputGolden(t, golden, "truncate ansi", NewTruncatedText("\x1b[31mred\x1b[0m and more", 1, 0).Render(9))
	checkInputGolden(t, golden, "truncate narrow", NewTruncatedText("abcdef", 2, 0).Render(4))
}

// TestLoaderAgainstUpstreamGolden verifies the loader rendering.
func TestLoaderAgainstUpstreamGolden(t *testing.T) {
	golden := loadSelectGolden(t)

	spinner := func(text string) string { return "<c>" + text + "</c>" }
	message := func(text string) string { return "<m>" + text + "</m>" }

	verbatim := NewLoader(nil, spinner, message, "Working", &LoaderIndicatorOptions{Frames: []string{"*"}, HasFrames: true, IntervalMS: 1000})
	checkInputGolden(t, golden, "loader verbatim", verbatim.Render(20))
	verbatim.Stop()

	custom := NewLoader(nil, spinner, message, "Working", &LoaderIndicatorOptions{Frames: []string{"x"}, HasFrames: true, IntervalMS: 1000})
	checkInputGolden(t, golden, "loader custom", custom.Render(20))
	custom.Stop()

	noFrame := NewLoader(nil, spinner, message, "Working", &LoaderIndicatorOptions{Frames: []string{}, HasFrames: true, IntervalMS: 1000})
	checkInputGolden(t, golden, "loader noframe", noFrame.Render(20))
	noFrame.SetMessage("Updated")
	checkInputGolden(t, golden, "loader message", noFrame.Render(20))
	noFrame.Stop()

	defaultFrames := NewLoader(nil, spinner, message, "Loading...", nil)
	defaultFrames.Stop()
	checkInputGolden(t, golden, "loader default-frame0", defaultFrames.Render(20))
}

// TestLoaderAnimation verifies that the animation advances and stops.
func TestLoaderAnimation(t *testing.T) {
	var renders atomic.Int64
	loader := NewLoader(&countingRequester{count: &renders}, identityFunc, identityFunc, "Working",
		&LoaderIndicatorOptions{Frames: []string{"1", "2", "3"}, HasFrames: true, IntervalMS: 5})
	first := loader.RenderedIndicator()
	deadline := 200
	for i := 0; i < deadline && loader.RenderedIndicator() == first; i++ {
		time.Sleep(5 * time.Millisecond)
	}
	if loader.RenderedIndicator() == first {
		t.Fatalf("animation did not advance from %q", first)
	}
	loader.Stop()
	stopped := loader.RenderedIndicator()
	time.Sleep(20 * time.Millisecond)
	if loader.RenderedIndicator() != stopped {
		t.Fatal("animation continued after stop")
	}
	if renders.Load() == 0 {
		t.Fatal("render was never requested")
	}
}

type countingRequester struct{ count *atomic.Int64 }

func (c *countingRequester) RequestRender(force bool) { c.count.Add(1) }

// TestCancellableLoader verifies the abort behaviour.
func TestCancellableLoader(t *testing.T) {
	loader := NewCancellableLoader(nil, identityFunc, identityFunc, "Working")
	aborted := false
	loader.OnAbort = func() { aborted = true }
	if loader.Aborted() {
		t.Fatal("must not start aborted")
	}
	loader.HandleInput("x")
	if loader.Aborted() {
		t.Fatal("plain key aborted the loader")
	}
	loader.HandleInput("\x1b")
	if !aborted || !loader.Aborted() {
		t.Fatal("escape did not abort")
	}
	select {
	case <-loader.Done():
	default:
		t.Fatal("done channel not closed")
	}
	loader.Dispose()
}

// TestMouseRegion verifies child-first dispatch.
func TestMouseRegion(t *testing.T) {
	child := &mouseRecordingComponent{}
	regionCalled := 0
	region := NewMouseRegion(child, func(event TuiMouseEvent) *TuiMouseDispatchResult {
		regionCalled++
		return &TuiMouseDispatchResult{TuiMouseEventResult: TuiMouseEventResult{Handled: true}}
	})

	if got := region.HandleMouse(TuiMouseEvent{Y: 0, Width: 10, Height: 1}); got == nil || regionCalled != 0 {
		t.Fatalf("child dispatch = %+v region=%d", got, regionCalled)
	}

	plain := NewMouseRegion(probe("x"), func(event TuiMouseEvent) *TuiMouseDispatchResult {
		regionCalled++
		return nil
	})
	regionCalled = 0
	if got := plain.HandleMouse(TuiMouseEvent{Y: 0, Width: 10, Height: 1}); got != nil {
		t.Fatalf("fallback = %+v", got)
	}
	if regionCalled != 1 {
		t.Fatalf("region calls = %d", regionCalled)
	}
	if lines := plain.Render(3); len(lines) != 1 || lines[0] != "x  " {
		t.Fatalf("render = %q", lines)
	}
	plain.Invalidate()
}

// TestAltScreenFlashAgainstUpstreamGolden verifies the flash rendering.
func TestAltScreenFlashAgainstUpstreamGolden(t *testing.T) {
	golden := loadSelectGolden(t)

	flashes := NewAltScreenFlashContainer(nil)
	flashes.Flash("saved", 100000)
	flashes.Flash("long message here", 100000)
	checkInputGolden(t, golden, "flash", flashes.Render(24))
	checkInputGolden(t, golden, "flash narrow", flashes.Render(6))
	flashes.Dispose()
	checkInputGolden(t, golden, "flash disposed", flashes.Render(24))
}

// TestLoaderRenderAdvancesFrame pins loop-mode animation: the frame is
// derived from the clock (RenderedIndicatorAt), so every Render must show the
// current frame. Upstream's own setInterval mutated the text between frames;
// in loop mode the owner's animation tick is the only mutator, and nothing
// calls updateDisplay between paints, so a cached frame froze the spinner
// (the frozen compaction spinner regression).
func TestLoaderRenderAdvancesFrame(t *testing.T) {
	loader := NewLoader(nil, identityFunc, identityFunc, "Working",
		&LoaderIndicatorOptions{Frames: []string{"A", "B"}, HasFrames: true, IntervalMS: 5})
	first := strings.Join(loader.Render(20), "\n")
	time.Sleep(15 * time.Millisecond)
	second := strings.Join(loader.Render(20), "\n")
	if first == second {
		t.Fatalf("Render did not advance the frame with the clock: %q", first)
	}
}
