package tui

import (
	"bufio"
	"os"
	"strconv"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream fuzzy matcher and
// SettingsList with Node. See tui/testdata/settings_golden.txt.

func loadSettingsGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/settings_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

// TestFuzzyAgainstUpstreamGolden verifies the fuzzy matcher scores.
func TestFuzzyAgainstUpstreamGolden(t *testing.T) {
	golden := loadSettingsGolden(t)

	queries := []string{"", "abc", "a", "ab", "foo", "fb", "sb", "x", "2a", "a2", "SET", "s-t", "s/t", "aa"}
	texts := []string{"abc", "a-b-c", "src/foo/bar.ts", "Settings", "setting-list", "a2b", "2ab", "abcabc", "", "ABC"}

	for _, query := range queries {
		for _, text := range texts {
			label := "fuzzy " + mustJSON(query) + " " + mustJSON(text)
			want, ok := golden[label]
			if !ok {
				t.Fatalf("missing golden %q", label)
			}
			match := MatchFuzzy(query, text)
			matches := "0"
			if match.Matches {
				matches = "1"
			}
			got := matches + " " + strconv.FormatFloat(match.Score, 'g', -1, 64)
			if got != want {
				t.Fatalf("%s:\n got %s\nwant %s", label, got, want)
			}
		}
	}

	type named struct{ name string }
	items := []named{{"alpha"}, {"beta"}, {"gamma"}, {"alphabet"}, {"src/foo/bar.ts"}}
	for _, query := range []string{"", "a", "al", "foo", "src/bar", "zz", "ta"} {
		label := "filter " + mustJSON(query)
		want, ok := golden[label]
		if !ok {
			t.Fatalf("missing golden %q", label)
		}
		filtered := FuzzyFilter(items, query, func(item named) string { return item.name })
		names := make([]string, 0, len(filtered))
		for _, item := range filtered {
			names = append(names, item.name)
		}
		if got := mustJSON(names); got != want {
			t.Fatalf("%s:\n got %s\nwant %s", label, got, want)
		}
	}
}

func settingsTestTheme() SettingsListTheme {
	return SettingsListTheme{
		Label: func(text string, selected bool) string {
			if selected {
				return "<l+>" + text + "</l+>"
			}
			return "<l>" + text + "</l>"
		},
		Value: func(text string, selected bool) string {
			if selected {
				return "<v+>" + text + "</v+>"
			}
			return "<v>" + text + "</v>"
		},
		Description: func(text string) string { return "<d>" + text + "</d>" },
		Cursor:      "> ",
		Hint:        func(text string) string { return "<h>" + text + "</h>" },
	}
}

func settingsTestItems() []SettingItem {
	return []SettingItem{
		{ID: "theme", Label: "Theme", CurrentValue: "dark", Values: []string{"dark", "light", "system"}, Description: "Color theme"},
		{ID: "model", Label: "Model", CurrentValue: "gpt", Description: "A longer description that should wrap across lines in narrow widths"},
		{ID: "verbose", Label: "Verbose logging", CurrentValue: "off", Values: []string{"off", "on"}},
		{ID: "sub", Label: "Submenu", CurrentValue: "open", Submenu: func(currentValue string, done func(result SubmenuResult)) Component {
			return &settingsSubmenu{currentValue: currentValue, done: done}
		}},
		{ID: "empty", Label: "Empty", CurrentValue: ""},
	}
}

// settingsSubmenu mimics the upstream probe submenu component.
type settingsSubmenu struct {
	currentValue string
	done         func(result SubmenuResult)
}

func (s *settingsSubmenu) Render(width int) []string {
	return []string{"submenu:" + s.currentValue}
}

func (s *settingsSubmenu) Invalidate() {}

func (s *settingsSubmenu) HandleInput(data string) {
	if data == "\x1b" {
		s.done(SubmenuResult{SelectedValue: "chosen", HasSelectedValue: true})
	}
}

// TestSettingsListAgainstUpstreamGolden verifies the settings list renders.
func TestSettingsListAgainstUpstreamGolden(t *testing.T) {
	golden := loadSettingsGolden(t)

	var changes []string
	onChange := func(id string, value string) { changes = append(changes, id+"="+value) }
	onCancel := func() { changes = append(changes, "cancel") }
	makeList := func(options SettingsListOptions, maxVisible int) *SettingsList {
		return NewSettingsList(settingsTestItems(), maxVisible, settingsTestTheme(), onChange, onCancel, options)
	}

	basic := makeList(SettingsListOptions{}, 4)
	checkInputGolden(t, golden, "settings basic", basic.Render(60))
	checkInputGolden(t, golden, "settings narrow", basic.Render(30))

	scrolled := makeList(SettingsListOptions{}, 2)
	scrolled.HandleInput("\x1b[B")
	checkInputGolden(t, golden, "settings scrolled", scrolled.Render(60))

	search := makeList(SettingsListOptions{EnableSearch: true}, 4)
	checkInputGolden(t, golden, "settings search", search.Render(60))
	search.HandleInput("m")
	checkInputGolden(t, golden, "settings search-filter", search.Render(60))
	search.HandleInput("\x7f")
	search.HandleInput("\x7f")
	checkInputGolden(t, golden, "settings search-cleared", search.Render(60))

	cycle := makeList(SettingsListOptions{}, 4)
	cycle.HandleInput("\r")
	changes = nil
	// The change was recorded before resetting; re-run to capture it.
	cycle = makeList(SettingsListOptions{}, 4)
	cycle.HandleInput("\r")
	checkInputGolden(t, golden, "settings cycle", mustJSON(cycle.Render(40)[0]))
	checkInputGolden(t, golden, "settings cycle-changes", changes)

	space := makeList(SettingsListOptions{}, 4)
	changes = nil
	space.HandleInput(" ")
	checkInputGolden(t, golden, "settings space-cycle", changes[len(changes)-1:])

	cancel := makeList(SettingsListOptions{}, 4)
	changes = nil
	cancel.HandleInput("\x1b")
	checkInputGolden(t, golden, "settings cancel", changes[len(changes)-1:])

	submenu := makeList(SettingsListOptions{}, 4)
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\r")
	checkInputGolden(t, golden, "settings submenu-open", submenu.Render(40))
	changes = nil
	submenu.HandleInput("\x1b")
	checkInputGolden(t, golden, "settings submenu-closed", submenu.Render(40))
	checkInputGolden(t, golden, "settings submenu-changes", changes)

	empty := NewSettingsList(nil, 4, settingsTestTheme(), onChange, onCancel, SettingsListOptions{})
	checkInputGolden(t, golden, "settings empty", empty.Render(40))
	emptySearch := NewSettingsList(nil, 4, settingsTestTheme(), onChange, onCancel, SettingsListOptions{EnableSearch: true})
	checkInputGolden(t, golden, "settings empty-search", emptySearch.Render(40))

	updated := makeList(SettingsListOptions{}, 4)
	updated.UpdateValue("model", "claude")
	updated.SelectItem("verbose")
	checkInputGolden(t, golden, "settings updated", updated.Render(60))
}

// TestSettingsListBehaviour verifies mouse handling and the search filter.
func TestSettingsListBehaviour(t *testing.T) {
	changes := 0
	list := NewSettingsList(settingsTestItems(), 4, settingsTestTheme(),
		func(id string, value string) { changes++ }, func() {}, SettingsListOptions{})

	// Wheel scrolling.
	before := list.SelectedIndex()
	result := list.HandleMouse(TuiMouseEvent{Type: MouseWheel, HasWheel: true, WheelDelta: 1, Width: 60, Height: 10})
	if result == nil || !result.Render || list.SelectedIndex() != before+1 {
		t.Fatalf("wheel = %+v index=%d", result, list.SelectedIndex())
	}
	// Hover ignored.
	if got := list.HandleMouse(TuiMouseEvent{Type: MouseMove, Button: MouseButtonLeft, Y: 2}); got != nil {
		t.Fatalf("move = %+v", got)
	}
	// Press focuses, click activates.
	press := list.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, Y: 0, Width: 60, Height: 10})
	if press == nil || !press.Focus {
		t.Fatalf("press = %+v", press)
	}
	click := list.HandleMouse(TuiMouseEvent{Type: MouseClick, Button: MouseButtonLeft, Y: 0, Width: 60, Height: 10})
	if click == nil || !click.Handled {
		t.Fatalf("click = %+v", click)
	}
	if changes != 1 {
		t.Fatalf("changes = %d", changes)
	}
	// Out-of-range rows ignored.
	if got := list.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, Y: 99, Width: 60, Height: 10}); got != nil {
		t.Fatalf("row = %+v", got)
	}

	// The search row routes presses to the search input.
	search := NewSettingsList(settingsTestItems(), 4, settingsTestTheme(),
		func(id string, value string) {}, func() {}, SettingsListOptions{EnableSearch: true})
	searchResult := search.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, X: 4, Y: 0, Width: 60, Height: 10})
	if searchResult == nil || !searchResult.Focus {
		t.Fatalf("search press = %+v", searchResult)
	}
	if got := search.HandleMouse(TuiMouseEvent{Type: MousePress, Button: MouseButtonLeft, Y: 1, Width: 60, Height: 10}); got != nil {
		t.Fatalf("padding row = %+v", got)
	}

	// Submenu input delegation keeps the list responsive.
	submenu := NewSettingsList(settingsTestItems(), 4, settingsTestTheme(),
		func(id string, value string) {}, func() {}, SettingsListOptions{})
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\r")
	submenu.HandleInput("ignored")
	if len(submenu.Render(20)) != 1 {
		t.Fatalf("submenu render = %q", submenu.Render(20))
	}

	// Up on an empty list is a no-op.
	empty := NewSettingsList(nil, 4, settingsTestTheme(), func(string, string) {}, func() {}, SettingsListOptions{})
	empty.HandleInput("\x1b[A")
	empty.HandleInput("\x1b[B")
	if empty.SelectedIndex() != 0 {
		t.Fatalf("index = %d", empty.SelectedIndex())
	}
}
