package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream implementation with
// Node: allocateStackSizes cases, VStack/HStack render outputs, and Text
// render outputs. See tui/testdata/layout_golden.txt.

func loadLayoutGolden(t *testing.T) (sizes map[string][]int, renders map[string][]string) {
	t.Helper()
	file, err := os.Open("testdata/layout_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()

	sizes = map[string][]int{}
	renders = map[string][]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		left, right := parts[0], parts[1]
		if strings.HasPrefix(left, "sizes ") {
			label := strings.TrimPrefix(left, "sizes ")
			var values []int
			if err := json.Unmarshal([]byte(right), &values); err != nil {
				t.Fatalf("bad sizes %q: %v", line, err)
			}
			sizes[label] = values
			continue
		}
		var values []string
		if err := json.Unmarshal([]byte(right), &values); err != nil {
			t.Fatalf("bad render %q: %v", line, err)
		}
		renders[left] = values
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return sizes, renders
}

// equalLines compares line slices treating nil and empty as equivalent.
func equalLines(got []string, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func equalInts(got []int, want []int) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func intPtrValue(v int) *int { return &v }

// TestAllocateStackSizesAgainstUpstreamGolden verifies the flex sizing
// algorithm against the upstream outputs.
func TestAllocateStackSizesAgainstUpstreamGolden(t *testing.T) {
	sizes, _ := loadLayoutGolden(t)

	entry := func(options StackEntryOptions) StackLayoutEntry {
		return NewStackEntry(&staticComponent{}, options)
	}

	cases := []struct {
		label     string
		entries   []StackLayoutEntry
		intrinsic []int
		available *int
		gap       int
	}{
		{"no-available", []StackLayoutEntry{entry(StackEntryOptions{}), entry(StackEntryOptions{}), entry(StackEntryOptions{})}, []int{2, 3, 4}, nil, 0},
		{"grow-default-none", []StackLayoutEntry{entry(StackEntryOptions{}), entry(StackEntryOptions{})}, []int{2, 3}, intPtrValue(20), 0},
		{"grow", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(1)}), entry(StackEntryOptions{Grow: intPtrValue(1)})}, []int{2, 3}, intPtrValue(20), 0},
		{"grow-weighted", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(1)}), entry(StackEntryOptions{Grow: intPtrValue(3)})}, []int{2, 3}, intPtrValue(20), 0},
		{"grow-with-gap", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(1)}), entry(StackEntryOptions{Grow: intPtrValue(1)})}, []int{2, 3}, intPtrValue(21), 1},
		{"grow-max", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(1), MaxSize: intPtrValue(5)}), entry(StackEntryOptions{Grow: intPtrValue(1)})}, []int{2, 3}, intPtrValue(30), 0},
		{"shrink", []StackLayoutEntry{entry(StackEntryOptions{}), entry(StackEntryOptions{})}, []int{10, 10}, intPtrValue(12), 0},
		{"shrink-min", []StackLayoutEntry{entry(StackEntryOptions{MinSize: intPtrValue(6)}), entry(StackEntryOptions{})}, []int{10, 10}, intPtrValue(8), 0},
		{"basis-fixed", []StackLayoutEntry{entry(StackEntryOptions{Basis: FixedBasis(5)}), entry(StackEntryOptions{})}, []int{1, 1}, intPtrValue(20), 0},
		{"basis-auto", []StackLayoutEntry{entry(StackEntryOptions{Basis: AutoBasis()}), entry(StackEntryOptions{})}, []int{4, 1}, intPtrValue(20), 0},
		{"grow-and-shrink", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(2)}), entry(StackEntryOptions{Shrink: intPtrValue(2)}), entry(StackEntryOptions{})}, []int{5, 15, 5}, intPtrValue(20), 1},
		{"clamp-negative", []StackLayoutEntry{entry(StackEntryOptions{Basis: FixedBasis(-3), MinSize: intPtrValue(1)}), entry(StackEntryOptions{})}, []int{1, 1}, intPtrValue(10), 0},
		{"min-over-max", []StackLayoutEntry{entry(StackEntryOptions{MinSize: intPtrValue(9), MaxSize: intPtrValue(4)}), entry(StackEntryOptions{})}, []int{1, 1}, intPtrValue(10), 0},
		{"zero-entries", nil, nil, intPtrValue(10), 0},
		{"single-grow", []StackLayoutEntry{entry(StackEntryOptions{Grow: intPtrValue(1)})}, []int{3}, intPtrValue(10), 0},
		{"shrink-below", []StackLayoutEntry{entry(StackEntryOptions{}), entry(StackEntryOptions{})}, []int{1, 1}, intPtrValue(0), 0},
	}

	for _, tc := range cases {
		want, ok := sizes[tc.label]
		if !ok {
			t.Fatalf("missing golden case %q", tc.label)
		}
		got := AllocateStackSizes(tc.entries, tc.intrinsic, tc.available, tc.gap)
		if !equalInts(got, want) {
			t.Fatalf("%s: got %v want %v", tc.label, got, want)
		}
	}
}

// sizedLinesComponent renders fixed lines padded to the width (the upstream
// probe component).
type sizedLinesComponent struct {
	lines []string
}

func (c *sizedLinesComponent) Render(width int) []string {
	out := make([]string, 0, len(c.lines))
	for _, line := range c.lines {
		if VisibleWidth(line) >= width {
			out = append(out, SliceByColumn(line, 0, width, true))
		} else {
			out = append(out, line+strings.Repeat(" ", width-VisibleWidth(line)))
		}
	}
	return out
}

func (c *sizedLinesComponent) Invalidate() {}

func linesComponent(lines ...string) Component { return &sizedLinesComponent{lines: lines} }

// TestStacksAgainstUpstreamGolden verifies the VStack/HStack render outputs.
func TestStacksAgainstUpstreamGolden(t *testing.T) {
	_, renders := loadLayoutGolden(t)

	intPtr := func(v int) *int { return &v }

	vstackGap := NewVStack(nil, StackOptions{Gap: intPtr(1)})
	vstackGap.AddChild(linesComponent("aa"))
	vstackGap.AddChild(linesComponent("bb"))

	vstackBasic := NewVStack([]Component{linesComponent("aa", "bb"), linesComponent("cc")}, StackOptions{})

	spacerZero := intPtr(0)
	vstackSpacer := NewVStack([]Component{linesComponent("aaa"), NewSpacer(2), linesComponent()}, StackOptions{Gap: spacerZero})

	vstackGap2 := NewVStack(nil, StackOptions{Gap: intPtr(2)})
	vstackGap2.AddChild(linesComponent("a"))
	vstackGap2.AddChild(linesComponent("b"))

	hstackBasic := NewHStack([]Component{linesComponent("a", "b"), linesComponent("x", "y")}, StackOptions{})
	hstackCenter := NewHStack([]Component{linesComponent("a"), linesComponent("x", "y")}, StackOptions{Align: "center"})
	hstackEnd := NewHStack([]Component{linesComponent("a"), linesComponent("x", "y")}, StackOptions{Align: "end"})

	hstackGap := NewHStack(nil, StackOptions{Gap: intPtr(1)})
	hstackGap.AddChild(linesComponent("ab"))
	hstackGap.AddChild(linesComponent("cd"))
	hstackEmpty := NewHStack(nil, StackOptions{})

	cases := []struct {
		label  string
		got    []string
		width  int
		render func() []string
	}{
		{"vstack-basic", nil, 4, func() []string { return vstackBasic.Render(4) }},
		{"vstack-gap", nil, 4, func() []string { return vstackGap.Render(4) }},
		{"vstack-spacer", nil, 3, func() []string { return vstackSpacer.Render(3) }},
		{"vstack-gap2", nil, 2, func() []string { return vstackGap2.Render(2) }},
		{"hstack-basic", nil, 4, func() []string { return hstackBasic.Render(4) }},
		{"hstack-align-center", nil, 4, func() []string { return hstackCenter.Render(4) }},
		{"hstack-align-end", nil, 4, func() []string { return hstackEnd.Render(4) }},
		{"hstack-gap", nil, 6, func() []string { return hstackGap.Render(6) }},
		{"hstack-empty", nil, 4, func() []string { return hstackEmpty.Render(4) }},
	}

	for _, tc := range cases {
		want, ok := renders[tc.label]
		if !ok {
			t.Fatalf("missing golden case %q", tc.label)
		}
		got := tc.render()
		if !equalLines(got, want) {
			t.Fatalf("%s: got %q want %q", tc.label, got, want)
		}
	}
}

// TestTextAgainstUpstreamGolden verifies the Text render outputs.
func TestTextAgainstUpstreamGolden(t *testing.T) {
	_, renders := loadLayoutGolden(t)

	cases := []struct {
		label string
		text  *Text
		width int
	}{
		{"text-basic", NewText("hello world", 1, 1, nil), 10},
		{"text-nowrap-pad", NewText("hello world", 0, 0, nil), 6},
		{"text-empty", NewText("", 1, 1, nil), 5},
		{"text-tab", NewText("a\tb", 1, 0, nil), 6},
		{"text-ansi", NewText("\x1b[31mred\x1b[0m", 1, 0, nil), 7},
		{"text-narrow", NewText("wide", 3, 0, nil), 4},
		{"text-bg", NewText("x", 0, 0, func(text string) string { return "\x1b[44m" + text + "\x1b[49m" }), 3},
	}

	for _, tc := range cases {
		want, ok := renders[tc.label]
		if !ok {
			t.Fatalf("missing golden case %q", tc.label)
		}
		got := tc.text.Render(tc.width)
		if !equalLines(got, want) {
			t.Fatalf("%s: got %q want %q", tc.label, got, want)
		}
	}
}

// TestStackLayoutNode verifies the layout-node view of a stack.
func TestStackLayoutNode(t *testing.T) {
	stack := NewVStack([]Component{linesComponent("a")}, StackOptions{Align: "center"})
	stack.AddChild(linesComponent("b"), StackEntryOptions{Grow: intPtrValue(2), Basis: FixedBasis(3)})

	node, ok := GetLayoutNode(stack)
	if !ok {
		t.Fatal("stack must provide a layout node")
	}
	if node.Kind != "vstack" || node.Stack == nil {
		t.Fatalf("node = %+v", node)
	}
	if node.Stack.Align != "center" || len(node.Stack.Entries) != 2 {
		t.Fatalf("node = %+v", node.Stack)
	}
	if node.Stack.Entries[1].Grow != 2 || node.Stack.Entries[1].Basis.Mode != "fixed" || node.Stack.Entries[1].Basis.Value != 3 {
		t.Fatalf("entry = %+v", node.Stack.Entries[1])
	}
	// Plain components have no layout node.
	if _, ok := GetLayoutNode(linesComponent("a")); ok {
		t.Fatal("plain component must not provide a layout node")
	}
}

// TestStackVisibility verifies the visible callback filtering.
func TestStackVisibility(t *testing.T) {
	stack := NewVStack(nil, StackOptions{})
	stack.AddChild(linesComponent("always"))
	stack.AddChild(linesComponent("conditional"), StackEntryOptions{
		Visible: func(viewport LayoutViewport) bool { return viewport.Width > 10 },
	})

	// At width 5 the conditional child is hidden.
	lines := stack.Render(5)
	if len(lines) != 1 {
		t.Fatalf("lines = %q", lines)
	}
	viewport := LayoutViewport{Width: 5, Height: 100}
	if visible := VisibleStackEntries(stack.Entries, viewport); len(visible) != 1 {
		t.Fatalf("visible = %d", len(visible))
	}
	viewport = LayoutViewport{Width: 50, Height: 100}
	if visible := VisibleStackEntries(stack.Entries, viewport); len(visible) != 2 {
		t.Fatalf("visible = %d", len(visible))
	}
}

// TestStackAddRemoveClear verifies entry bookkeeping.
func TestStackAddRemoveClear(t *testing.T) {
	first := linesComponent("a")
	second := linesComponent("b")
	stack := NewVStack([]Component{first}, StackOptions{})
	stack.AddChild(second)
	if len(stack.Entries) != 2 || len(stack.Children) != 2 {
		t.Fatalf("entries = %d children = %d", len(stack.Entries), len(stack.Children))
	}
	stack.RemoveChild(first)
	if len(stack.Entries) != 1 || stack.Entries[0].Component != second {
		t.Fatalf("entries = %+v", stack.Entries)
	}
	stack.Clear()
	if len(stack.Entries) != 0 || len(stack.Children) != 0 {
		t.Fatal("clear failed")
	}
}

// TestSpacer verifies the spacer component.
func TestSpacer(t *testing.T) {
	spacer := NewSpacer(3)
	if got := spacer.Render(10); !equalLines(got, []string{"", "", ""}) {
		t.Fatalf("render = %q", got)
	}
	spacer.SetLines(1)
	if got := spacer.Render(10); !equalLines(got, []string{""}) {
		t.Fatalf("render = %q", got)
	}
}
