package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/dat267/pier/ai"
	"github.com/dat267/pier/coding"
)

// The golden file is generated by running the upstream session search, oauth
// selector, and login dialog with Node
// (coding/interactive/testdata/auth_golden.txt).

type sessionSpec struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Text     string `json:"text"`
	Cwd      string `json:"cwd"`
	Modified int64  `json:"modified"`
}

type oauthProviderSpec struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	AuthType string `json:"authType"`
	Status   *struct {
		Type   string `json:"type"`
		Source string `json:"source"`
	} `json:"status"`
}

type oauthSpec struct {
	Mode      string              `json:"mode"`
	Width     int                 `json:"width"`
	Providers []oauthProviderSpec `json:"providers"`
	Search    string              `json:"search"`
	Inputs    []string            `json:"inputs"`
}

type loginSpec struct {
	Width      int      `json:"width"`
	DeviceCode []string `json:"deviceCode"`
	Info       []any    `json:"info"`
	Waiting    string   `json:"waiting"`
	Details    []string `json:"details"`
	Progress   string   `json:"progress"`
	Prompt     []string `json:"prompt"`
}

type authCorpus struct {
	Sessions []sessionSpec        `json:"sessions"`
	Queries  []string             `json:"queries"`
	OAuth    map[string]oauthSpec `json:"oauth"`
	Login    map[string]loginSpec `json:"login"`
}

func loadAuthGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/auth_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "a ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkAuthGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	if strings.HasPrefix(label, "parse ") {
		if projected, ok := got.(map[string]any); ok {
			if message, isString := projected["error"].(string); isString && message != "" && message != "Empty regex" {
				projected["error"] = "regex error"
			}
		}
		if strings.Contains(want, "Unterminated group") || strings.Contains(want, "Invalid regular expression") {
			want = `{"error":"regex error","mode":"regex","regex":null,"tokens":[]}`
		}
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestSessionSearchAgainstUpstreamGolden replays the query parsing, matching,
// and filtering.
func TestSessionSearchAgainstUpstreamGolden(t *testing.T) {
	golden := loadAuthGolden(t)
	data, err := os.ReadFile("testdata/auth_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := authCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	sessions := make([]coding.SessionInfo, 0, len(corpus.Sessions))
	for _, spec := range corpus.Sessions {
		sessions = append(sessions, coding.SessionInfo{
			ID: spec.ID, Path: spec.ID, Name: spec.Name, Cwd: spec.Cwd,
			AllMessagesText: spec.Text, Modified: time.UnixMilli(spec.Modified),
		})
	}

	for _, query := range corpus.Queries {
		parsed := ParseSearchQuery(query)
		tokens := parsed.Tokens
		if tokens == nil {
			tokens = []SearchToken{}
		}
		var parseError any
		if parsed.Error != "" {
			parseError = parsed.Error
			// The V8 regexp error wording differs from Go's (D93); only the
			// empty-pattern message is reproduced verbatim.
			if parsed.Mode == "regex" && parsed.Error != "Empty regex" {
				parseError = "Invalid regular expression"
			}
		}
		projection := map[string]any{
			"mode": parsed.Mode, "tokens": tokens, "error": parseError, "regex": regexSource(parsed),
		}
		checkAuthGolden(t, golden, "parse "+mustJSON(query), projection)

		matches := make([]map[string]any, 0, len(sessions))
		for _, session := range sessions {
			result := MatchSession(session, parsed)
			matches = append(matches, map[string]any{"matches": result.Matches, "score": result.Score})
		}
		checkAuthGolden(t, golden, "match "+mustJSON(query), matches)

		for _, mode := range []SortMode{SortThreaded, SortRecent, SortRelevance} {
			ids := make([]string, 0, len(sessions))
			for _, session := range FilterAndSortSessions(sessions, query, mode, NameFilterNamed) {
				ids = append(ids, session.ID)
			}
			checkAuthGolden(t, golden, "filter "+mustJSON(query)+" "+string(mode)+" named", ids)
		}
		allIDs := make([]string, 0, len(sessions))
		for _, session := range FilterAndSortSessions(sessions, query, SortRelevance, NameFilterAll) {
			allIDs = append(allIDs, session.ID)
		}
		checkAuthGolden(t, golden, "filter "+mustJSON(query)+" relevance all", allIDs)
	}

	names := make([]bool, 0, len(sessions))
	for _, session := range sessions {
		names = append(names, HasSessionName(session))
	}
	checkAuthGolden(t, golden, "hasName", names)
}

func regexSource(parsed ParsedSearchQuery) any {
	if parsed.Regex == nil {
		return nil
	}
	return parsed.Pattern
}

// TestOAuthSelectorAgainstUpstreamGolden replays the auth selector renders.
func TestOAuthSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadAuthGolden(t)
	data, err := os.ReadFile("testdata/auth_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := authCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.OAuth) {
		spec := corpus.OAuth[label]
		providers := make([]AuthSelectorProvider, 0, len(spec.Providers))
		for _, provider := range spec.Providers {
			entry := AuthSelectorProvider{ID: provider.ID, Name: provider.Name, AuthType: provider.AuthType}
			if provider.Status != nil {
				entry.Status = &ai.AuthCheck{Type: provider.Status.Type, Source: provider.Status.Source}
			}
			providers = append(providers, entry)
		}
		component := NewOAuthSelectorComponent(spec.Mode, providers, nil, nil, spec.Search)
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkAuthGolden(t, golden, "oauth "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}
	checkAuthGolden(t, golden, "authtype", []string{
		FormatAuthSelectorProviderType("oauth"), FormatAuthSelectorProviderType("api_key"),
	})
}

// TestLoginDialogAgainstUpstreamGolden replays the login dialog states.
func TestLoginDialogAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadAuthGolden(t)
	data, err := os.ReadFile("testdata/auth_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := authCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Login) {
		spec := corpus.Login[label]
		component := NewLoginDialogComponent(nil, nil, "openai", nil, "", "")
		if len(spec.DeviceCode) == 2 {
			component.ShowDeviceCode(spec.DeviceCode[0], spec.DeviceCode[1])
		}
		if len(spec.Info) >= 1 {
			message, _ := spec.Info[0].(string)
			var links []ai.AuthInfoLink
			showCloseHint := false
			if len(spec.Info) >= 2 {
				if rawLinks, ok := spec.Info[1].([]any); ok {
					for _, rawLink := range rawLinks {
						if pair, ok := rawLink.([]any); ok && len(pair) == 2 {
							url, _ := pair[0].(string)
							label, _ := pair[1].(string)
							links = append(links, ai.AuthInfoLink{URL: url, Label: label})
						}
					}
				}
			}
			if len(spec.Info) >= 3 {
				showCloseHint, _ = spec.Info[2].(bool)
			}
			component.ShowInfo(message, links, showCloseHint)
		}
		if spec.Waiting != "" {
			component.ShowWaiting(spec.Waiting)
		}
		if spec.Details != nil {
			component.ShowDetails(spec.Details)
		}
		if spec.Progress != "" {
			component.ShowProgress(spec.Progress)
		}
		if len(spec.Prompt) == 2 {
			component.ShowPrompt(spec.Prompt[0], spec.Prompt[1])
		}
		checkAuthGolden(t, golden, "login "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}
}

// TestLoginDialogCancellation covers the cancel path and the result channel.
func TestLoginDialogCancellation(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	InitTheme("dark", false)

	var completed []string
	component := NewLoginDialogComponent(nil, nil, "test", func(success bool, message string) {
		completed = append(completed, message)
	}, "", "")
	results := component.ShowPrompt("code?", "")
	component.HandleInput("\x1b")
	select {
	case result := <-results:
		if result.Err == nil {
			t.Fatal("expected cancellation error")
		}
	case <-time.After(time.Second):
		t.Fatal("prompt did not resolve")
	}
	select {
	case <-component.Aborted():
	default:
		t.Fatal("aborted channel not closed")
	}
	if len(completed) != 1 || completed[0] != "Login cancelled" {
		t.Fatalf("completed = %v", completed)
	}

	// Submitting resolves the prompt with the value.
	component2 := NewLoginDialogComponent(nil, nil, "test", nil, "", "")
	results2 := component2.ShowPrompt("code?", "")
	component2.HandleInput("a")
	component2.HandleInput("\r")
	select {
	case result := <-results2:
		if result.Err != nil || result.Value != "a" {
			t.Fatalf("result = %+v", result)
		}
	case <-time.After(time.Second):
		t.Fatal("prompt did not resolve")
	}
}

// TestBrowserOpenerHook verifies the injected browser opener (D92).
func TestBrowserOpenerHook(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	InitTheme("dark", false)
	var opened []string
	SetBrowserOpener(func(url string) { opened = append(opened, url) })
	defer SetBrowserOpener(nil)

	component := NewLoginDialogComponent(nil, nil, "test", nil, "", "")
	component.ShowAuth("https://example.com/auth", "instructions")
	if len(opened) != 1 || opened[0] != "https://example.com/auth" {
		t.Fatalf("opened = %v", opened)
	}
	if lines := component.Render(40); len(lines) < 3 {
		t.Fatalf("render = %q", lines)
	}
}
