package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/gpi/tui"
)

// The golden file is generated by running the upstream interactive components
// with Node (coding/interactive/testdata/components_golden.txt).

type truncateSpec struct {
	Text  string `json:"text"`
	Max   int    `json:"max"`
	Width int    `json:"width"`
	Pad   *int   `json:"pad"`
}

type userMessageSpec struct {
	Text  string `json:"text"`
	Width int    `json:"width"`
	Pad   *int   `json:"pad"`
}

type customEntrySpec struct {
	Type  string `json:"type"`
	Width int    `json:"width"`
}

type componentsCorpus struct {
	Keybindings   []string          `json:"keybindings"`
	RawKeys       []string          `json:"rawKeys"`
	BorderWidths  []int             `json:"borderWidths"`
	Truncate      []truncateSpec    `json:"truncate"`
	UserMessages  []userMessageSpec `json:"userMessages"`
	CustomEntries []customEntrySpec `json:"customEntries"`
}

func loadComponentsGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/components_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "c ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkComponentsGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestComponentsAgainstUpstreamGolden replays the upstream component corpus.
func TestComponentsAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	// The Node probe reports truecolor support and chalk colors (its
	// capability stub plus FORCE_COLOR), so the Go side matches.
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadComponentsGolden(t)
	data, err := os.ReadFile("testdata/components_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := componentsCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, keybinding := range corpus.Keybindings {
		checkComponentsGolden(t, golden, "keytext "+keybinding, []string{
			KeyText(keybinding), KeyDisplayText(keybinding), KeyHint(keybinding, "description"),
		})
	}
	for _, raw := range corpus.RawKeys {
		checkComponentsGolden(t, golden, "rawkey "+raw, []string{
			FormatKeyText(raw, KeyTextFormatOptions{}),
			FormatKeyText(raw, KeyTextFormatOptions{Capitalize: true}),
			RawKeyHint(raw, "hint"),
		})
	}

	for _, width := range corpus.BorderWidths {
		checkComponentsGolden(t, golden, "border@"+itoa(width), NewDynamicBorder(nil).Render(width))
		checkComponentsGolden(t, golden, "border-red@"+itoa(width), NewDynamicBorder(func(s string) string {
			return "<" + s + ">"
		}).Render(width))
	}

	for index, spec := range corpus.Truncate {
		padding := 0
		if spec.Pad != nil {
			padding = *spec.Pad
		}
		result := TruncateToVisualLines(spec.Text, spec.Max, spec.Width, padding)
		lines := result.VisualLines
		if lines == nil {
			lines = []string{}
		}
		checkComponentsGolden(t, golden, "truncate"+itoa(index), []any{lines, result.SkippedCount})
	}

	for index, spec := range corpus.UserMessages {
		padding := 1
		if spec.Pad != nil {
			padding = *spec.Pad
		}
		component := NewUserMessageComponent(spec.Text, nil, padding, nil)
		checkComponentsGolden(t, golden, "user"+itoa(index)+"@"+itoa(spec.Width),
			normalizeRender(component.Render(spec.Width)))
	}

	renderer := func(entry CustomEntry, options EntryRenderOptions, theme *Theme) tui.Component {
		state := "collapsed"
		if options.Expanded {
			state = "expanded"
		}
		return tui.NewText("custom:"+entry.CustomType+":"+state, 0, 0, nil)
	}
	for index, spec := range corpus.CustomEntries {
		component := NewCustomEntryComponent(CustomEntry{CustomType: spec.Type}, renderer)
		checkComponentsGolden(t, golden, "custom"+itoa(index)+"-collapsed@"+itoa(spec.Width),
			normalizeRender(component.Render(spec.Width)))
		checkComponentsGolden(t, golden, "custom"+itoa(index)+"-hasContent", component.HasContent())
		component.SetExpanded(true)
		checkComponentsGolden(t, golden, "custom"+itoa(index)+"-expanded@"+itoa(spec.Width),
			normalizeRender(component.Render(spec.Width)))
	}

	failing := NewCustomEntryComponent(CustomEntry{CustomType: "broken"}, func(entry CustomEntry, options EntryRenderOptions, theme *Theme) tui.Component {
		panic("boom")
	})
	checkComponentsGolden(t, golden, "custom-failed", normalizeRender(failing.Render(30)))
	empty := NewCustomEntryComponent(CustomEntry{CustomType: "empty"}, func(entry CustomEntry, options EntryRenderOptions, theme *Theme) tui.Component {
		return nil
	})
	checkComponentsGolden(t, golden, "custom-empty", []any{empty.HasContent(), normalizeRender(empty.Render(20))})

	loader := NewBorderedLoader(nil, ActiveTheme(), "Working...", nil)
	loader.Dispose()
	checkComponentsGolden(t, golden, "loader@30", normalizeRender(loader.Render(30)))
	plain := false
	plainLoader := NewBorderedLoader(nil, ActiveTheme(), "Plain", &plain)
	plainLoader.Dispose()
	checkComponentsGolden(t, golden, "loader-plain@30", normalizeRender(plainLoader.Render(30)))
}

func normalizeRender(lines []string) []string {
	if lines == nil {
		return []string{}
	}
	return lines
}

// TestThemeFactories verifies the theme-derived factories.
func TestThemeFactories(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	InitTheme("dark", false)

	markdown := GetMarkdownTheme()
	if markdown.Heading == nil || markdown.Bold == nil || markdown.HighlightCode == nil {
		t.Fatal("markdown theme incomplete")
	}
	if got := markdown.Bold("x"); got != "\x1b[1mx\x1b[22m" {
		t.Fatalf("bold = %q", got)
	}
	lines := markdown.HighlightCode("a\nb", "go")
	if len(lines) != 2 || !strings.Contains(lines[0], "a") {
		t.Fatalf("highlight = %v", lines)
	}
	selectTheme := GetSelectListTheme()
	if selectTheme.SelectedText == nil {
		t.Fatal("select list theme incomplete")
	}
	editorTheme := GetEditorTheme()
	if editorTheme.BorderColor == nil || editorTheme.SelectList.SelectedText == nil {
		t.Fatal("editor theme incomplete")
	}
	settingsTheme := GetSettingsListTheme()
	if settingsTheme.Cursor == "" {
		t.Fatal("settings theme incomplete")
	}

	colors, err := GetResolvedThemeColors("dark")
	if err != nil {
		t.Fatalf("resolved colors: %v", err)
	}
	if colors["accent"] != "#8abeb7" {
		t.Fatalf("accent = %q", colors["accent"])
	}
	pageBg, _, _, err := GetThemeExportColors("dark")
	if err != nil {
		t.Fatalf("export colors: %v", err)
	}
	if pageBg != "#18181e" {
		t.Fatalf("pageBg = %q", pageBg)
	}
	if !IsLightTheme("light") || IsLightTheme("dark") {
		t.Fatal("light theme detection")
	}

	if language, ok := GetLanguageFromPath("src/main.go"); !ok || language != "go" {
		t.Fatalf("language = %q %v", language, ok)
	}
	if _, ok := GetLanguageFromPath("noext"); ok {
		t.Fatal("extensionless path matched")
	}
	if _, ok := GetLanguageFromPath("file."); ok {
		t.Fatal("trailing dot matched")
	}
}
