package interactive

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/dat267/pier/coding"
)

// The golden file is generated by running the upstream config selector with
// Node (coding/interactive/testdata/config_golden.txt). Both sides use the same
// fixed working directories so the rendered paths stay deterministic.

const (
	configProbeCwd   = "/tmp/pier-cfg/cwd"
	configProbeAgent = "/tmp/pier-cfg/agent"
)

type configMetadataJSON struct {
	Source  string `json:"source"`
	Scope   string `json:"scope"`
	Origin  string `json:"origin"`
	BaseDir string `json:"baseDir"`
}

type configResourceJSON struct {
	Path     string             `json:"path"`
	Enabled  bool               `json:"enabled"`
	Metadata configMetadataJSON `json:"metadata"`
}

type configPathsJSON struct {
	Extensions []configResourceJSON `json:"extensions"`
	Skills     []configResourceJSON `json:"skills"`
	Prompts    []configResourceJSON `json:"prompts"`
	Themes     []configResourceJSON `json:"themes"`
}

type configCorpus struct {
	Resolved struct {
		Global  configPathsJSON `json:"global"`
		Project configPathsJSON `json:"project"`
	} `json:"resolved"`
	Cases map[string]struct {
		Width                int             `json:"width"`
		TerminalHeight       int             `json:"terminalHeight"`
		WriteScope           string          `json:"writeScope"`
		ProjectModeAvailable *bool           `json:"projectModeAvailable"`
		Inputs               []string        `json:"inputs"`
		GlobalSettings       json.RawMessage `json:"globalSettings"`
		ProjectSettings      json.RawMessage `json:"projectSettings"`
	} `json:"cases"`
}

func (p configPathsJSON) toResolvedPaths() ResolvedPaths {
	convert := func(resources []configResourceJSON) []ResolvedResource {
		result := make([]ResolvedResource, 0, len(resources))
		for _, resource := range resources {
			result = append(result, ResolvedResource{
				Path:    resource.Path,
				Enabled: resource.Enabled,
				Metadata: coding.PathMetadata{
					Source:  resource.Metadata.Source,
					Scope:   resource.Metadata.Scope,
					Origin:  resource.Metadata.Origin,
					BaseDir: resource.Metadata.BaseDir,
				},
			})
		}
		return result
	}
	return ResolvedPaths{
		Extensions: convert(p.Extensions),
		Skills:     convert(p.Skills),
		Prompts:    convert(p.Prompts),
		Themes:     convert(p.Themes),
	}
}

// configSettingsProjection serializes only the resource keys, mirroring the
// upstream probe's projection.
func configSettingsProjection(settings *coding.Settings) any {
	result := map[string]any{}
	if settings.Extensions != nil {
		result["extensions"] = settings.Extensions
	}
	if settings.Skills != nil {
		result["skills"] = settings.Skills
	}
	if settings.Prompts != nil {
		result["prompts"] = settings.Prompts
	}
	if settings.Themes != nil {
		result["themes"] = settings.Themes
	}
	if settings.Packages != nil {
		result["packages"] = settings.Packages
	}
	return result
}

// TestConfigSelectorAgainstUpstreamGolden replays the config selector renders
// and the persisted settings after every input.
func TestConfigSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/config_golden.txt")
	data, err := os.ReadFile("testdata/config_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := configCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	resolved := ScopedResolvedPaths{
		Global:  corpus.Resolved.Global.toResolvedPaths(),
		Project: corpus.Resolved.Project.toResolvedPaths(),
	}

	for _, label := range sortedKeys(corpus.Cases) {
		spec := corpus.Cases[label]
		if err := os.RemoveAll("/tmp/pier-cfg"); err != nil {
			t.Fatalf("clean probe dirs: %v", err)
		}
		if err := os.MkdirAll(filepath.Join(configProbeCwd, ".pi"), 0o755); err != nil {
			t.Fatalf("mkdir cwd: %v", err)
		}
		if err := os.MkdirAll(configProbeAgent, 0o755); err != nil {
			t.Fatalf("mkdir agent: %v", err)
		}
		writeJSONFile(t, filepath.Join(configProbeAgent, "settings.json"), spec.GlobalSettings)
		writeJSONFile(t, filepath.Join(configProbeCwd, ".pi", "settings.json"), spec.ProjectSettings)

		manager := coding.NewSettingsManagerFromFiles(configProbeCwd, configProbeAgent, coding.SettingsManagerCreateOptions{})
		writeScope := spec.WriteScope
		if writeScope == "" {
			writeScope = ConfigWriteScopeGlobal
		}
		projectModeAvailable := true
		if spec.ProjectModeAvailable != nil {
			projectModeAvailable = *spec.ProjectModeAvailable
		}
		component := NewConfigSelectorComponent(resolved, manager, configProbeCwd, configProbeAgent,
			func() {}, func() {}, func() {}, spec.TerminalHeight, writeScope, projectModeAvailable)
		list := component.GetResourceList()

		checkEasterGolden(t, golden, label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		for index, input := range spec.Inputs {
			list.HandleInput(input)
			encoded, _ := json.Marshal(input)
			checkEasterGolden(t, golden, label+"+"+itoa(index)+"+"+string(encoded)+"@"+itoa(spec.Width),
				normalizeRender(component.Render(spec.Width)))
		}
		checkEasterGolden(t, golden, label+"-global", configSettingsProjection(manager.GetGlobalSettings()))
		checkEasterGolden(t, golden, label+"-project", configSettingsProjection(manager.GetProjectSettings()))
	}
}

func writeJSONFile(t *testing.T, path string, content json.RawMessage) {
	t.Helper()
	if len(content) == 0 {
		content = json.RawMessage("{}")
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

// TestConfigSelectorHelpers covers the pure grouping helpers.
func TestConfigSelectorHelpers(t *testing.T) {
	resolved := ResolvedPaths{
		Extensions: []ResolvedResource{
			{Path: "/base/extensions/one/index.ts", Enabled: true,
				Metadata: coding.PathMetadata{Source: "auto", Scope: "user", Origin: "top-level", BaseDir: "/base"}},
			{Path: "/base/extensions/two.ts", Enabled: false,
				Metadata: coding.PathMetadata{Source: "npm:pkg", Scope: "user", Origin: "package", BaseDir: "/base/npm:pkg"}},
		},
		Skills: []ResolvedResource{
			{Path: "/base/skills/alpha/SKILL.md", Enabled: true,
				Metadata: coding.PathMetadata{Source: "auto", Scope: "user", Origin: "top-level", BaseDir: "/base"}},
			{Path: "/base/skills/beta.md", Enabled: true,
				Metadata: coding.PathMetadata{Source: "auto", Scope: "user", Origin: "top-level", BaseDir: "/base"}},
		},
	}
	groups := buildGroups(resolved, "/agent")
	if len(groups) != 2 {
		t.Fatalf("groups = %d", len(groups))
	}
	// Packages sort before top-level.
	if groups[0].Origin != "package" || groups[1].Origin != "top-level" {
		t.Fatalf("group order = %s, %s", groups[0].Origin, groups[1].Origin)
	}
	topLevel := groups[1]
	if topLevel.Label != "User (/base/)" {
		t.Fatalf("label = %q", topLevel.Label)
	}
	if len(topLevel.Subgroups) != 2 || topLevel.Subgroups[0].Type != "extensions" || topLevel.Subgroups[1].Type != "skills" {
		t.Fatalf("subgroups = %+v", topLevel.Subgroups)
	}
	skillNames := []string{}
	for _, item := range topLevel.Subgroups[1].Items {
		skillNames = append(skillNames, item.DisplayName)
	}
	if len(skillNames) != 2 || skillNames[0] != "alpha" || skillNames[1] != "beta.md" {
		t.Fatalf("skill names = %v", skillNames)
	}
	extensionNames := []string{}
	for _, item := range topLevel.Subgroups[0].Items {
		extensionNames = append(extensionNames, item.DisplayName)
	}
	if len(extensionNames) != 1 || extensionNames[0] != "one/index.ts" {
		t.Fatalf("extension names = %v", extensionNames)
	}

	if got := getGroupLabel(coding.PathMetadata{Source: "auto", Scope: "user", Origin: "top-level"}, "/agent"); got != "User (/agent/)" {
		t.Fatalf("auto user label = %q", got)
	}
	if got := getGroupLabel(coding.PathMetadata{Source: "auto", Scope: "project", Origin: "top-level"}, "/agent"); got != "Project (.pi/)" {
		t.Fatalf("auto project label = %q", got)
	}
	if got := getGroupLabel(coding.PathMetadata{Source: "npm:x", Scope: "project", Origin: "package"}, "/agent"); got != "npm:x (project)" {
		t.Fatalf("package label = %q", got)
	}
	if got := getGroupLabel(coding.PathMetadata{Source: "settings", Scope: "user", Origin: "top-level"}, "/agent"); got != "User settings" {
		t.Fatalf("settings label = %q", got)
	}
	if got := getGroupLabel(coding.PathMetadata{Source: "settings", Scope: "project", Origin: "top-level"}, "/agent"); got != "Project settings" {
		t.Fatalf("project settings label = %q", got)
	}

	if !configIsLocalPath("/tmp/x") || configIsLocalPath("npm:x") || configIsLocalPath("https://x") {
		t.Fatal("configIsLocalPath mismatch")
	}
	if patternEntryTarget("+a/b") != "a/b" || patternEntryTarget("!a/b") != "a/b" || patternEntryTarget("a/b") != "a/b" {
		t.Fatal("patternEntryTarget mismatch")
	}
}

// TestConfigPackageSourceRoundTrip covers the settings `packages` view.
func TestConfigPackageSourceRoundTrip(t *testing.T) {
	fromString := packageSourceOf("npm:foo")
	if fromString.IsObject || fromString.Source != "npm:foo" {
		t.Fatalf("string source = %+v", fromString)
	}
	if fromString.ToAny(false) != "npm:foo" {
		t.Fatalf("string round trip = %#v", fromString.ToAny(false))
	}

	autoload := false
	fromObject := packageSourceOf(coding.SettingsPackageSource{
		Source: "npm:bar", Autoload: &autoload, Extensions: []string{"+a.ts"},
	})
	if !fromObject.IsObject || !fromObject.AutoloadFalse() || !fromObject.HasFilters() {
		t.Fatalf("object source = %+v", fromObject)
	}
	fromObject.SetFilters(ResourceTypeExtensions, nil)
	if fromObject.HasFilters() {
		t.Fatal("filters not cleared")
	}
	// autoload false keeps the object when requested.
	kept, ok := fromObject.ToAny(true).(coding.SettingsPackageSource)
	if !ok || kept.Autoload == nil || *kept.Autoload {
		t.Fatalf("kept = %#v", kept)
	}
	if fromObject.ToAny(false) != "npm:bar" {
		t.Fatalf("object round trip = %#v", fromObject.ToAny(false))
	}

	// A JSON-decoded object (map) behaves the same.
	decoded := map[string]any{"source": "npm:baz", "skills": []any{"-x.md"}}
	fromMap := packageSourceOf(decoded)
	if fromMap.Source != "npm:baz" || len(fromMap.Filters[ResourceTypeSkills]) != 1 {
		t.Fatalf("map source = %+v", fromMap)
	}
}
