package interactive

import (
	"encoding/json"
	"os"
	"runtime"
	"testing"

	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream custom editor with Node
// (coding/interactive/testdata/customeditor_golden.txt).

type customEditorCorpus struct {
	Render map[string]struct {
		Embed     bool    `json:"embed"`
		Indicator *string `json:"indicator"`
		Hidden    int     `json:"hidden"`
		Width     int     `json:"width"`
		Text      string  `json:"text"`
	} `json:"render"`
	Input map[string]struct {
		Text    string   `json:"text"`
		Inputs  []string `json:"inputs"`
		Actions []struct {
			Name string `json:"name"`
		} `json:"actions"`
		ExtensionShortcut string `json:"extensionShortcut"`
	} `json:"input"`
}

// editorTestHost is a minimal tui.EditorHost.
type editorTestHost struct{}

func (editorTestHost) Rows() int                { return 24 }
func (editorTestHost) RequestRender(force bool) {}

// TestCustomEditorAgainstUpstreamGolden replays the border renders and the
// input routing.
func TestCustomEditorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/customeditor_golden.txt")
	data, err := os.ReadFile("testdata/customeditor_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := customEditorCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	keybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(keybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	theme := ActiveTheme()
	editorTheme := tui.EditorTheme{
		BorderColor: func(text string) string { return theme.Fg("border", text) },
	}

	for _, label := range sortedKeys(corpus.Render) {
		spec := corpus.Render[label]
		editor := NewCustomEditor(editorTestHost{}, editorTheme, keybindings, CustomEditorOptions{
			EmbedWorkingStatus: spec.Embed,
		})
		if spec.Indicator != nil {
			editor.SetWorkingStatusIndicator(NewStatusIndicator("working", editorTestHost{},
				func(text string) string { return theme.Fg("accent", text) },
				func(text string) string { return theme.Fg("muted", text) },
				*spec.Indicator, nil))
		}
		editor.SetText(spec.Text)
		checkEasterGolden(t, golden, "render "+label+"@"+itoa(spec.Width)+"/"+itoa(spec.Hidden),
			editor.renderTopBorder(spec.Width, spec.Hidden))
	}

	for _, label := range sortedKeys(corpus.Input) {
		spec := corpus.Input[label]
		// The paste-image binding is platform-keyed (pasteImageKeys(windows)), and
		// this golden recorded the Unix key, so replaying it there asserts the
		// other labels without inventing a second recording.
		if runtime.GOOS == "windows" && label == "paste-image" {
			continue
		}
		editor := NewCustomEditor(editorTestHost{}, editorTheme, keybindings, CustomEditorOptions{})
		editor.SetText(spec.Text)
		var events []string
		editor.OnEscape = func() { events = append(events, "escape") }
		editor.OnCtrlD = func() { events = append(events, "ctrlD") }
		editor.OnPasteImage = func() { events = append(events, "pasteImage") }
		extensionShortcut := spec.ExtensionShortcut
		editor.OnExtensionShortcut = func(data string) bool {
			if extensionShortcut != "" && data == extensionShortcut {
				events = append(events, "ext:"+data)
				return true
			}
			return false
		}
		for _, action := range spec.Actions {
			actionName := action.Name
			editor.OnAction(tui.Keybinding(actionName), func() {
				events = append(events, "action:"+actionName)
			})
		}
		for _, input := range spec.Inputs {
			editor.HandleInput(input)
		}
		if events == nil {
			events = []string{}
		}
		checkEasterGolden(t, golden, "input "+label, []any{events, editor.GetText()})
	}
}
