package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The golden file is generated by running the real jsdiff (`diff` package)
// and the upstream renderDiff with Node
// (coding/interactive/testdata/diff_golden.txt).

func loadDiffGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/diff_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "d ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkDiffGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestDiffAgainstUpstreamGolden compares DiffWords and RenderDiff with jsdiff.
func TestDiffAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadDiffGolden(t)
	data, err := os.ReadFile("testdata/diff_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := struct {
		Words   map[string][2]string `json:"words"`
		Renders map[string]string    `json:"renders"`
	}{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	labels := make([]string, 0, len(corpus.Words))
	for label := range corpus.Words {
		labels = append(labels, label)
	}
	sortStrings(labels)
	for _, label := range labels {
		pair := corpus.Words[label]
		changes := DiffWords(pair[0], pair[1])
		projected := make([]map[string]any, 0, len(changes))
		for _, change := range changes {
			projected = append(projected, map[string]any{
				"value": change.Value, "added": change.Added, "removed": change.Removed,
			})
		}
		checkDiffGolden(t, golden, "words "+label, projected)
	}

	renderLabels := make([]string, 0, len(corpus.Renders))
	for label := range corpus.Renders {
		renderLabels = append(renderLabels, label)
	}
	sortStrings(renderLabels)
	for _, label := range renderLabels {
		got := RenderDiff(corpus.Renders[label], RenderDiffOptions{})
		checkDiffGolden(t, golden, "render "+label, got)
	}
}

// TestDiffHelpers covers the pure helpers.
func TestDiffHelpers(t *testing.T) {
	if prefix := longestCommonPrefix("abcde", "abxyz"); prefix != "ab" {
		t.Fatalf("prefix = %q", prefix)
	}
	if suffix := longestCommonSuffix("abcde", "xycde"); suffix != "cde" {
		t.Fatalf("suffix = %q", suffix)
	}
	if suffix := longestCommonSuffix("", "abc"); suffix != "" {
		t.Fatalf("empty suffix = %q", suffix)
	}
	if got := leadingWs("  x  "); got != "  " {
		t.Fatalf("leadingWs = %q", got)
	}
	if got := trailingWs("  x  "); got != "  " {
		t.Fatalf("trailingWs = %q", got)
	}
	if got := removeSuffix("abcdef", "def"); got != "abc" {
		t.Fatalf("removeSuffix = %q", got)
	}
	if got := removePrefix("abcdef", "abc"); got != "def" {
		t.Fatalf("removePrefix = %q", got)
	}
	if got := maximumOverlap("abab", "abab"); got != "abab" {
		t.Fatalf("maximumOverlap = %q", got)
	}
	if parsed, ok := parseDiffLine("-12 content here"); !ok || parsed.prefix != "-" || parsed.lineNum != "12" || parsed.content != "content here" {
		t.Fatalf("parsed = %+v ok=%v", parsed, ok)
	}
	if _, ok := parseDiffLine("no prefix"); ok {
		t.Fatal("unprefixed line parsed")
	}
	if got := replaceTabs("a\tb"); got != "a   b" {
		t.Fatalf("replaceTabs = %q", got)
	}
}
