package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/gpi/tui"
)

// The golden file is generated by running the upstream skill/first-time-setup/
// announcement components with Node
// (coding/interactive/testdata/easter_golden.txt).

type skillSpec struct {
	Name    string `json:"name"`
	Content string `json:"content"`
	Width   int    `json:"width"`
}

type setupSpec struct {
	Detected string   `json:"detected"`
	Inputs   []string `json:"inputs"`
	Width    int      `json:"width"`
}

type easterCorpus struct {
	Skill map[string]skillSpec `json:"skill"`
	Setup map[string]setupSpec `json:"setup"`
}

func loadEasterGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/easter_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "x ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkEasterGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestEasterComponentsAgainstUpstreamGolden replays the skill/setup/
// announcement renders.
func TestEasterComponentsAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadEasterGolden(t)
	data, err := os.ReadFile("testdata/easter_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := easterCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Skill) {
		spec := corpus.Skill[label]
		component := NewSkillInvocationMessageComponent(spec.Name, spec.Content, nil)
		checkEasterGolden(t, golden, "skill "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		component.SetExpanded(true)
		checkEasterGolden(t, golden, "skill "+label+"-expanded@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}

	for _, label := range sortedKeys(corpus.Setup) {
		spec := corpus.Setup[label]
		var previews []string
		component := NewFirstTimeSetupComponent(FirstTimeSetupOptions{
			DetectedTheme:  TerminalTheme(spec.Detected),
			OnThemePreview: func(themeName string) { previews = append(previews, themeName) },
		})
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkEasterGolden(t, golden, "setup "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		previewProjection := previews
		if previewProjection == nil {
			previewProjection = []string{}
		}
		checkEasterGolden(t, golden, "setup "+label+"-previews", previewProjection)
	}

	checkEasterGolden(t, golden, "announcement@60", normalizeRender(NewEarendilAnnouncementComponent().Render(60)))
}

// TestEasterDeterministicParts covers the daxnuts/armin image data.
func TestEasterDeterministicParts(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	if len(daxnutsRGBHexData) != daxnutsWidth*daxnutsHeight*6 {
		t.Fatalf("daxnuts data length = %d", len(daxnutsRGBHexData))
	}
	pixels := parseDaxnutsPixels()
	if len(pixels) != daxnutsHeight || len(pixels[0]) != daxnutsWidth {
		t.Fatalf("pixels = %dx%d", len(pixels), len(pixels[0]))
	}
	image := buildDaxnutsImage()
	if len(image) != daxnutsHeight/2 {
		t.Fatalf("image rows = %d", len(image))
	}
	if !strings.Contains(image[0], "▄") || !strings.Contains(image[0], "\x1b[48;2;") {
		t.Fatalf("image line = %q", image[0])
	}

	// The daxnuts reveal is a pure function of the tick.
	component := NewDaxnutsComponent(nil)
	first := component.Render(40)
	if len(first) == 0 {
		t.Fatal("empty render")
	}
	if got := component.Render(40); len(got) != len(first) {
		t.Fatal("cache mismatch")
	}
	component.SetTick(5)
	mid := component.Render(40)
	if len(mid) != len(first) {
		t.Fatalf("tick render rows = %d", len(mid))
	}
	component.SetTick(25)
	final := component.Render(40)
	if !strings.Contains(strings.Join(final, "\n"), "Free Kimi K2.5 via OpenCode Zen") {
		t.Fatal("final text missing")
	}

	// Armin: the final grid is deterministic and the render pads to the width.
	grid := ArminFinalGrid()
	if len(grid) != (arminHeight+1)/2 || len(grid[0]) != arminWidth {
		t.Fatalf("armin grid = %dx%d", len(grid), len(grid[0]))
	}
	armin := NewArminComponent(nil, "typewriter", 1)
	armin.SetGrid(grid)
	lines := armin.Render(40)
	if len(lines) != len(grid)+1 {
		t.Fatalf("armin lines = %d", len(lines))
	}
	if !strings.HasPrefix(lines[0], " ") || tui.VisibleWidth(lines[len(lines)-1]) > 41 {
		t.Fatalf("armin padding: %q", lines[0])
	}
	if !strings.Contains(lines[len(lines)-1], "ARMIN SAYS HI") {
		t.Fatalf("armin message missing: %q", lines[len(lines)-1])
	}
	if _, ok := findNonSpace(grid); !ok {
		t.Fatal("armin grid is empty")
	}
}

func findNonSpace(grid [][]string) (string, bool) {
	for _, row := range grid {
		for _, cell := range row {
			if cell != " " {
				return cell, true
			}
		}
	}
	return "", false
}
