package interactive

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/dat267/gpi/ai"
	"github.com/dat267/gpi/coding"
)

// The golden file is generated by running the upstream footer component with
// Node (coding/interactive/testdata/footer_golden.txt). Both sides load the
// same session JSONL fixture.

const footerProbeSessionPath = "/tmp/gpi-footer/session.jsonl"

type footerSpecJSON struct {
	Width         int       `json:"width"`
	Cwd           string    `json:"cwd"`
	Model         *ai.Model `json:"model"`
	ThinkingLevel string    `json:"thinkingLevel"`
	ContextUsage  *struct {
		Tokens        *int64   `json:"tokens"`
		ContextWindow int64    `json:"contextWindow"`
		Percent       *float64 `json:"percent"`
	} `json:"contextUsage"`
	Branch        string            `json:"branch"`
	SessionName   string            `json:"sessionName"`
	ProviderCount int               `json:"providerCount"`
	Statuses      map[string]string `json:"statuses"`
	Subscriptions []string          `json:"subscriptions"`
	AutoCompact   *bool             `json:"autoCompact"`
}

type footerCorpus struct {
	Tokens map[string]struct {
		Count int64 `json:"count"`
	} `json:"tokens"`
	Cwd map[string]struct {
		Cwd  string `json:"cwd"`
		Home string `json:"home"`
	} `json:"cwd"`
	Footer       map[string]footerSpecJSON `json:"footer"`
	SessionJSONL string                    `json:"sessionJsonl"`
}

// fakeFooterSession implements FooterSession over a real session manager.
type fakeFooterSession struct {
	manager       *coding.SessionManager
	model         *ai.Model
	thinkingLevel string
	contextUsage  *coding.ContextUsageReport
	subscriptions map[string]bool
}

func (f *fakeFooterSession) Model() *ai.Model { return f.model }

func (f *fakeFooterSession) ThinkingLevel() ai.ThinkingLevel { return f.thinkingLevel }

func (f *fakeFooterSession) SessionManager() *coding.SessionManager { return f.manager }

func (f *fakeFooterSession) GetContextUsage() *coding.ContextUsageReport { return f.contextUsage }

func (f *fakeFooterSession) IsUsingSubscription(providerID string) bool {
	return f.subscriptions[providerID]
}

// fakeFooterData implements coding.ReadonlyFooterDataProvider.
type fakeFooterData struct {
	branch        string
	hasBranch     bool
	statuses      map[string]string
	providerCount int
}

func (f *fakeFooterData) GetGitBranch() (string, bool) { return f.branch, f.hasBranch }

func (f *fakeFooterData) GetExtensionStatuses() map[string]string { return f.statuses }

func (f *fakeFooterData) GetAvailableProviderCount() int { return f.providerCount }

func (f *fakeFooterData) OnBranchChange(func()) func() { return func() {} }

// TestFooterAgainstUpstreamGolden replays the footer renders and the pure
// formatting helpers.
func TestFooterAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/footer_golden.txt")
	data, err := os.ReadFile("testdata/footer_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := footerCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Tokens) {
		checkEasterGolden(t, golden, "tokens "+label, FormatTokens(corpus.Tokens[label].Count))
	}
	for _, label := range sortedKeys(corpus.Cwd) {
		spec := corpus.Cwd[label]
		checkEasterGolden(t, golden, "cwd "+label, FormatCwdForFooter(spec.Cwd, spec.Home))
	}

	if err := os.MkdirAll("/tmp/gpi-footer", 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(footerProbeSessionPath, []byte(corpus.SessionJSONL), 0o644); err != nil {
		t.Fatalf("write session: %v", err)
	}
	manager, err := coding.OpenSession(footerProbeSessionPath, "", "")
	if err != nil {
		t.Fatalf("open session: %v", err)
	}

	for _, label := range sortedKeys(corpus.Footer) {
		spec := corpus.Footer[label]
		session := &fakeFooterSession{
			manager:       manager,
			model:         spec.Model,
			thinkingLevel: spec.ThinkingLevel,
			subscriptions: map[string]bool{},
		}
		for _, provider := range spec.Subscriptions {
			session.subscriptions[provider] = true
		}
		if spec.ContextUsage != nil {
			session.contextUsage = &coding.ContextUsageReport{
				Tokens:        spec.ContextUsage.Tokens,
				ContextWindow: spec.ContextUsage.ContextWindow,
				Percent:       spec.ContextUsage.Percent,
			}
		}
		dataProvider := &fakeFooterData{
			branch:        spec.Branch,
			hasBranch:     spec.Branch != "",
			statuses:      spec.Statuses,
			providerCount: spec.ProviderCount,
		}
		if dataProvider.statuses == nil {
			dataProvider.statuses = map[string]string{}
		}
		footer := NewFooterComponent(session, dataProvider)
		if spec.AutoCompact != nil {
			footer.SetAutoCompactEnabled(*spec.AutoCompact)
		}
		checkEasterGolden(t, golden, "footer "+label+"@"+itoa(spec.Width),
			normalizeRender(footer.Render(spec.Width)))
	}
}

// TestAgentSessionSatisfiesFooterSession guards the seam.
func TestAgentSessionSatisfiesFooterSession(t *testing.T) {
	var _ FooterSession = (*coding.AgentSession)(nil)
}
