package interactive

import (
	"bufio"
	"context"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/dat267/pier/ai"
	"github.com/dat267/pier/coding"
)

// The golden file is generated by running the upstream model selectors with
// Node against a fake model runtime (coding/interactive/testdata/
// modelsel_golden.txt).

type modelSelectorSpec struct {
	Current         *int     `json:"current"`
	Default         *int     `json:"default"`
	Scoped          []int    `json:"scoped"`
	Search          string   `json:"search"`
	SelectAsDefault bool     `json:"selectAsDefault"`
	Inputs          []string `json:"inputs"`
	Width           int      `json:"width"`
}

type scopedSelectorSpec struct {
	Enabled       []int    `json:"enabled"`
	RefreshStatus string   `json:"refreshStatus"`
	Inputs        []string `json:"inputs"`
	Width         int      `json:"width"`
}

type modelselCorpus struct {
	Model  map[string]modelSelectorSpec  `json:"model"`
	Scoped map[string]scopedSelectorSpec `json:"scoped"`
}

type fakeModelRuntime struct {
	models []*ai.Model
}

func (f *fakeModelRuntime) GetAvailableSnapshot() []*ai.Model { return f.models }

func (f *fakeModelRuntime) GetModel(providerID string, modelID string) *ai.Model {
	for _, model := range f.models {
		if string(model.Provider) == providerID && model.ID == modelID {
			return model
		}
	}
	return nil
}

func (f *fakeModelRuntime) GetError() string { return "" }

// Refresh blocks until the context is cancelled so the pre-refresh status
// line stays stable while the test renders (the upstream probe renders before
// its fire-and-forget refresh resolves).
func (f *fakeModelRuntime) Refresh(ctx context.Context, options *coding.ModelsRefreshCallOptions) (ai.ModelsRefreshResult, error) {
	<-ctx.Done()
	return ai.ModelsRefreshResult{Aborted: true}, ctx.Err()
}

func loadModelSelGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/modelsel_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "m ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkModelSelGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

func testModels() []*ai.Model {
	return []*ai.Model{
		{Provider: "openai", ID: "gpt-5", Name: "GPT-5", API: "openai", Reasoning: true},
		{Provider: "openai", ID: "gpt-4o", Name: "GPT-4o", API: "openai"},
		{Provider: "anthropic", ID: "claude-3", Name: "Claude 3", API: "anthropic", Reasoning: true},
	}
}

// TestModelSelectorsAgainstUpstreamGolden replays the selectors.
func TestModelSelectorsAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadModelSelGolden(t)
	data, err := os.ReadFile("testdata/modelsel_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := modelselCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	models := testModels()
	runtime := &fakeModelRuntime{models: models}

	for _, label := range sortedKeys(corpus.Model) {
		spec := corpus.Model[label]
		var current *ai.Model
		if spec.Current != nil {
			current = models[*spec.Current]
		}
		var scoped []ScopedModelItem
		for _, index := range spec.Scoped {
			scoped = append(scoped, ScopedModelItem{Model: models[index]})
		}
		var defaultModel *DefaultModelReference
		if spec.Default != nil {
			defaultModel = &DefaultModelReference{Provider: string(models[*spec.Default].Provider), ID: models[*spec.Default].ID}
		}
		var onSelectAsDefault func(*ai.Model)
		if spec.SelectAsDefault {
			onSelectAsDefault = func(*ai.Model) {}
		}
		component := NewModelSelectorComponent(nil, current, runtime, scoped, func(*ai.Model) {}, func() {},
			spec.Search, onSelectAsDefault, defaultModel)
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkModelSelGolden(t, golden, "modelsel "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		component.Dispose()
	}

	for _, label := range sortedKeys(corpus.Scoped) {
		spec := corpus.Scoped[label]
		var enabled *EnabledIds
		if spec.Enabled != nil {
			ids := EnabledIds{IDs: []string{}}
			for _, index := range spec.Enabled {
				ids.IDs = append(ids.IDs, string(models[index].Provider)+"/"+models[index].ID)
			}
			enabled = &ids
		}
		component := NewScopedModelsSelectorComponent(ModelsConfig{
			AllModels: models, EnabledModelIDs: enabled, RefreshStatus: spec.RefreshStatus,
		}, ModelsCallbacks{})
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkModelSelGolden(t, golden, "scoped "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}
}

// TestEnabledIDHelpers covers the pure enable/disable/reorder helpers.
func TestEnabledIDHelpers(t *testing.T) {
	all := []string{"a", "b", "c"}

	// Toggling off the only enabled id from "all" yields the explicit list.
	if got := toggleEnabled(EnabledIds{All: true}, all, "b"); got.All || strings.Join(got.IDs, ",") != "a,c" {
		t.Fatalf("toggle = %+v", got)
	}
	// Re-enabling the last missing id collapses back to "all".
	if got := toggleEnabled(EnabledIds{IDs: []string{"a", "c"}}, all, "b"); !got.All {
		t.Fatalf("normalize = %+v", got)
	}
	if got := enableAllModels(EnabledIds{IDs: []string{"a"}}, all, nil, false); !got.All {
		t.Fatalf("enableAll = %+v", got)
	}
	if got := enableAllModels(EnabledIds{All: true}, all, nil, false); !got.All {
		t.Fatalf("enableAll from all = %+v", got)
	}
	if got := clearAllModels(EnabledIds{All: true}, all, nil, false); len(got.IDs) != 0 {
		t.Fatalf("clearAll = %+v", got)
	}
	if got := clearAllModels(EnabledIds{All: true}, all, []string{"b"}, true); strings.Join(got.IDs, ",") != "a,c" {
		t.Fatalf("clearAll targets = %+v", got)
	}
	if got := moveEnabled(EnabledIds{IDs: []string{"a", "b", "c"}}, "b", -1); strings.Join(got.IDs, ",") != "b,a,c" {
		t.Fatalf("move = %+v", got)
	}
	if got := moveEnabled(EnabledIds{IDs: []string{"a", "b", "c"}}, "a", -1); strings.Join(got.IDs, ",") != "a,b,c" {
		t.Fatalf("move out of range = %+v", got)
	}
	if got := moveEnabled(EnabledIds{All: true}, "a", 1); !got.All {
		t.Fatalf("move from all = %+v", got)
	}
	if got := getSortedIDs(EnabledIds{IDs: []string{"c"}}, all); strings.Join(got, ",") != "c,a,b" {
		t.Fatalf("sorted = %v", got)
	}
}

// TestModelSelectorSelectNoDeadlock guards D137: selecting a model must not
// deadlock on the component's state mutex (Dispose re-locks) and the onSelect
// callback runs outside the lock.
func TestModelSelectorSelectNoDeadlock(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	models := testModels()
	runtime := &fakeModelRuntime{models: models}
	selected := make(chan *ai.Model, 1)
	var component *ModelSelectorComponent
	component = NewModelSelectorComponent(nil, models[0], runtime, nil, func(model *ai.Model) {
		// Callbacks may touch the component (render/dispose) without deadlocking.
		component.Dispose()
		_ = component.Render(80)
		selected <- model
	}, func() {}, "", nil, nil)

	done := make(chan struct{})
	go func() {
		defer close(done)
		component.HandleInput("\r")
	}()
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("HandleInput deadlocked while selecting a model")
	}
	select {
	case model := <-selected:
		if model == nil || model.ID != models[0].ID {
			t.Fatalf("selected = %+v", model)
		}
	case <-time.After(time.Second):
		t.Fatal("onSelect not called")
	}
}
