package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"runtime"
	"strings"
	"testing"

	"github.com/dat267/pier/coding"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream selector components
// with Node (coding/interactive/testdata/selector_golden.txt).

type themeSpec struct {
	Current string `json:"current"`
	Width   int    `json:"width"`
}

type imagesSpec struct {
	Current bool `json:"current"`
	Width   int  `json:"width"`
}

type thinkingSpec struct {
	Current string   `json:"current"`
	Default string   `json:"default"`
	Inputs  []string `json:"inputs"`
	Width   int      `json:"width"`
}

type userMessagesSpec struct {
	Messages []string `json:"messages"`
	Initial  string   `json:"initial"`
	Inputs   []string `json:"inputs"`
	Width    int      `json:"width"`
}

type trustSpec struct {
	Cwd           string                         `json:"cwd"`
	SavedDecision *coding.ProjectTrustStoreEntry `json:"savedDecision"`
	Trusted       bool                           `json:"trusted"`
	Inputs        []string                       `json:"inputs"`
	Width         int                            `json:"width"`
}

type customSpec struct {
	Type     string `json:"type"`
	Content  any    `json:"content"`
	Renderer string `json:"renderer"`
	Width    int    `json:"width"`
}

type selectorCorpus struct {
	Theme        map[string]themeSpec        `json:"theme"`
	Images       map[string]imagesSpec       `json:"images"`
	Thinking     map[string]thinkingSpec     `json:"thinking"`
	UserMessages map[string]userMessagesSpec `json:"userMessages"`
	Trust        map[string]trustSpec        `json:"trust"`
	Custom       map[string]customSpec       `json:"custom"`
}

func loadSelectorGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/selector_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "s ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkSelectorGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestSelectorsAgainstUpstreamGolden replays the upstream selector corpus.
func TestSelectorsAgainstUpstreamGolden(t *testing.T) {
	// The corpus drives Unix paths (/tmp/project) and the golden bakes in how
	// they render, so the trust prompt's parent-folder label and the paths come
	// out with the platform separator here and cannot match a Unix recording.
	if runtime.GOOS == "windows" {
		t.Skip("the golden embeds Unix paths")
	}
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadSelectorGolden(t)
	data, err := os.ReadFile("testdata/selector_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := selectorCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Theme) {
		spec := corpus.Theme[label]
		component := NewThemeSelectorComponent(spec.Current, nil, nil, nil)
		checkSelectorGolden(t, golden, "theme "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		selected, _ := component.GetSelectList().GetSelectedItem()
		checkSelectorGolden(t, golden, "theme "+label+"-selected", selected)
	}

	for _, label := range sortedKeys(corpus.Images) {
		spec := corpus.Images[label]
		component := NewShowImagesSelectorComponent(spec.Current, nil, nil)
		checkSelectorGolden(t, golden, "images "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}

	levels := []string{"off", "minimal", "low", "medium", "high", "xhigh", "max"}
	for _, label := range sortedKeys(corpus.Thinking) {
		spec := corpus.Thinking[label]
		component := NewThinkingSelectorComponent(spec.Current, levels, nil, nil, nil, spec.Default)
		component.SetFocused(true)
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkSelectorGolden(t, golden, "thinking "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		selected, _ := component.GetSelectList().GetSelectedItem()
		checkSelectorGolden(t, golden, "thinking "+label+"-selected", selected)
	}

	for _, label := range sortedKeys(corpus.UserMessages) {
		spec := corpus.UserMessages[label]
		items := make([]UserMessageItem, 0, len(spec.Messages))
		for index, text := range spec.Messages {
			items = append(items, UserMessageItem{ID: itoa(index), Text: text})
		}
		component := NewUserMessageSelectorComponent(items, nil, nil, spec.Initial, nil)
		for _, input := range spec.Inputs {
			component.GetMessageList().HandleInput(input)
		}
		checkSelectorGolden(t, golden, "umsg "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}

	for _, label := range sortedKeys(corpus.Trust) {
		spec := corpus.Trust[label]
		component := NewTrustSelectorComponent(TrustSelectorOptions{
			Cwd: spec.Cwd, SavedDecision: spec.SavedDecision, ProjectTrusted: spec.Trusted,
		})
		for _, input := range spec.Inputs {
			component.HandleInput(input)
		}
		checkSelectorGolden(t, golden, "trust "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}

	for _, label := range sortedKeys(corpus.Custom) {
		spec := corpus.Custom[label]
		payload := CustomMessagePayload{CustomType: spec.Type}
		switch content := spec.Content.(type) {
		case string:
			payload.Text = content
		case []any:
			for _, block := range content {
				if entry, ok := block.(map[string]any); ok {
					if text, ok := entry["text"].(string); ok {
						payload.Blocks = append(payload.Blocks, text)
					}
				}
			}
		}
		var renderer MessageRenderer
		switch spec.Renderer {
		case "throw":
			renderer = func(message CustomMessagePayload, options MessageRenderOptions, theme *Theme) tui.Component {
				panic("boom")
			}
		case "none":
		default:
			renderer = func(message CustomMessagePayload, options MessageRenderOptions, theme *Theme) tui.Component {
				state := "c"
				if options.Expanded {
					state = "e"
				}
				return tui.NewText("custom:"+message.CustomType+":"+state, 0, 0, nil)
			}
		}
		component := NewCustomMessageComponent(payload, renderer, nil, 1)
		checkSelectorGolden(t, golden, "custom "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		component.SetExpanded(true)
		checkSelectorGolden(t, golden, "custom "+label+"-expanded@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
	}
}
