package interactive

import (
	"context"
	"encoding/json"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/dat267/pier/coding"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream session selector with
// Node (coding/interactive/testdata/session_golden.txt). Relative ages are
// derived from a per-run "now", so the corpus stores the age offsets.

type sessionSpecJSON struct {
	Path              string `json:"path"`
	ID                string `json:"id"`
	Cwd               string `json:"cwd"`
	Name              string `json:"name"`
	ParentSessionPath string `json:"parentSessionPath"`
	ModifiedAgoMs     int64  `json:"modifiedAgoMs"`
	MessageCount      int    `json:"messageCount"`
	FirstMessage      string `json:"firstMessage"`
	AllMessagesText   string `json:"allMessagesText"`
}

type sessionCaseJSON struct {
	Width                  int               `json:"width"`
	CurrentSessions        []sessionSpecJSON `json:"currentSessions"`
	AllSessions            []sessionSpecJSON `json:"allSessions"`
	CurrentSessionFilePath string            `json:"currentSessionFilePath"`
	Inputs                 []string          `json:"inputs"`
	LoadError              string            `json:"loadError"`
	Progress               []int             `json:"progress"`
	CanRename              *bool             `json:"canRename"`
	ShowRenameHint         *bool             `json:"showRenameHint"`
}

type sessionCorpus struct {
	Cases map[string]sessionCaseJSON `json:"cases"`
}

func toSessionInfos(specs []sessionSpecJSON, now time.Time) []coding.SessionInfo {
	result := make([]coding.SessionInfo, 0, len(specs))
	for _, spec := range specs {
		modified := now.Add(-time.Duration(spec.ModifiedAgoMs) * time.Millisecond)
		result = append(result, coding.SessionInfo{
			Path:              spec.Path,
			ID:                spec.ID,
			Cwd:               spec.Cwd,
			Name:              spec.Name,
			ParentSessionPath: spec.ParentSessionPath,
			Created:           modified,
			Modified:          modified,
			MessageCount:      spec.MessageCount,
			FirstMessage:      spec.FirstMessage,
			AllMessagesText:   spec.AllMessagesText,
		})
	}
	return result
}

// TestSessionSelectorAgainstUpstreamGolden replays the session selector
// renders, callbacks and rename traces.
func TestSessionSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/session_golden.txt")
	data, err := os.ReadFile("testdata/session_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := sessionCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	// The app keybindings must be installed globally, exactly like the
	// interactive mode does (the list reads app.* bindings from there).
	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	for _, label := range sortedKeys(corpus.Cases) {
		spec := corpus.Cases[label]
		if label == "narrow" {
			// The one upstream render the port deliberately does not reproduce:
			// at 44 columns upstream truncates the header's controls and squeezes
			// the message beside its metadata, and the port stacks both instead
			// (D158). TestSessionSelectorHeaderStacksOnNarrowTerminals and
			// TestSessionListUsesTwoLineRowsOnNarrowTerminals pin the replacement.
			continue
		}
		// A fixed "now" keeps the relative ages stable while still matching
		// the probe's Date.now()-based offsets.
		now := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)
		current := toSessionInfos(spec.CurrentSessions, now)
		all := toSessionInfos(spec.AllSessions, now)
		if spec.AllSessions == nil {
			all = current
		}

		var events []string
		var renames []string
		currentLoader := func(onProgress SessionListProgress, ctx context.Context) ([]coding.SessionInfo, error) {
			if spec.LoadError != "" {
				return nil, errString(spec.LoadError)
			}
			if len(spec.Progress) == 2 {
				onProgress(spec.Progress[0], spec.Progress[1], nil)
			}
			return current, nil
		}
		allLoader := func(onProgress SessionListProgress, ctx context.Context) ([]coding.SessionInfo, error) {
			if spec.LoadError != "" {
				return nil, errString(spec.LoadError)
			}
			return all, nil
		}

		queue := &postQueue{}
		options := SessionSelectorOptions{
			Keybindings:            appKeybindings.KeybindingsManager,
			CurrentSessionFilePath: spec.CurrentSessionFilePath,
			Now:                    func() time.Time { return now },
			ScheduleTimer:          func(ms int, fn func()) {},
			Post:                   queue.Post,
		}
		canRename := true
		if spec.CanRename != nil {
			canRename = *spec.CanRename
		}
		if canRename {
			options.RenameSession = func(sessionPath string, currentName string) error {
				renames = append(renames, sessionPath+"="+currentName)
				return nil
			}
		}
		if spec.ShowRenameHint != nil {
			options.ShowRenameHint = *spec.ShowRenameHint
		}

		component := NewSessionSelectorComponent(currentLoader, allLoader,
			func(sessionPath string) { events = append(events, "select:"+sessionPath) },
			func() { events = append(events, "cancel") },
			func() { events = append(events, "exit") },
			func() {}, options)
		component.WaitForPendingLoads()
		queue.drain()

		checkEasterGolden(t, golden, label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		for index, input := range spec.Inputs {
			component.HandleInput(input)
			component.WaitForPendingLoads()
			queue.drain()
			encoded, _ := json.Marshal(input)
			checkEasterGolden(t, golden, label+"+"+itoa(index)+"+"+string(encoded)+"@"+itoa(spec.Width),
				normalizeRender(component.Render(spec.Width)))
		}
		if events == nil {
			events = []string{}
		}
		if renames == nil {
			renames = []string{}
		}
		checkEasterGolden(t, golden, label+"-events", events)
		checkEasterGolden(t, golden, label+"-renames", renames)
	}
}

type errString string

func (e errString) Error() string { return string(e) }

// TestSessionSelectorHelpers covers the pure helpers and the tree building.
func TestSessionSelectorHelpers(t *testing.T) {
	now := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)
	cases := []struct {
		ago  time.Duration
		want string
	}{
		{30 * time.Second, "now"},
		{5 * time.Minute, "5m"},
		{3 * time.Hour, "3h"},
		{2 * 24 * time.Hour, "2d"},
		{20 * 24 * time.Hour, "2w"},
		{45 * 24 * time.Hour, "1mo"},
		{400 * 24 * time.Hour, "1y"},
	}
	for _, testCase := range cases {
		if got := formatSessionDate(now.Add(-testCase.ago), now); got != testCase.want {
			t.Fatalf("age(%v) = %q, want %q", testCase.ago, got, testCase.want)
		}
	}
	if got := shortenSessionPath(""); got != "" {
		t.Fatalf("shorten empty = %q", got)
	}
	if got := shortenSessionPath("/tmp/x"); got != "/tmp/x" {
		t.Fatalf("shorten tmp = %q", got)
	}
	home, _ := os.UserHomeDir()
	if home != "" {
		if got := shortenSessionPath(home + "/x"); got != "~/x" {
			t.Fatalf("shorten home = %q", got)
		}
	}

	sessions := []coding.SessionInfo{
		{Path: "/s/root.jsonl", Modified: now.Add(-time.Hour)},
		{Path: "/s/child.jsonl", ParentSessionPath: "/s/root.jsonl", Modified: now.Add(-2 * time.Hour)},
		{Path: "/s/other.jsonl", Modified: now.Add(-3 * time.Hour)},
		{Path: "/s/orphan.jsonl", ParentSessionPath: "/s/missing.jsonl", Modified: now.Add(-4 * time.Hour)},
	}
	roots := buildSessionTree(sessions)
	if len(roots) != 3 {
		t.Fatalf("roots = %d", len(roots))
	}
	// The root with the most recent activity in its subtree sorts first.
	if roots[0].Session.Path != "/s/root.jsonl" {
		t.Fatalf("first root = %q", roots[0].Session.Path)
	}
	if len(roots[0].Children) != 1 || roots[0].Children[0].Session.Path != "/s/child.jsonl" {
		t.Fatalf("children = %+v", roots[0].Children)
	}
	flat := flattenSessionTree(roots)
	if len(flat) != 4 {
		t.Fatalf("flat = %d", len(flat))
	}
	if flat[0].Depth != 0 || flat[1].Depth != 1 {
		t.Fatalf("depths = %d, %d", flat[0].Depth, flat[1].Depth)
	}
	if flat[1].IsLast != true {
		t.Fatalf("child isLast = %v", flat[1].IsLast)
	}
	if got := (&SessionList{}).buildTreePrefix(flatSessionNode{Depth: 2, IsLast: false, AncestorContinues: []bool{true, false}}); got != "│  "+"   "+"├─ " {
		t.Fatalf("prefix = %q", got)
	}
	if got := stripControlCharacters("a\x01b\x7fc"); got != "a b c" {
		t.Fatalf("strip = %q", got)
	}
}

// TestSessionSelectorDeleteFlow checks the confirmation and deletion plumbing
// with an injected deleter (D102).
func TestSessionSelectorDeleteFlow(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	now := time.Now()
	sessions := []coding.SessionInfo{
		{Path: "/s/a.jsonl", FirstMessage: "a", Modified: now},
		{Path: "/s/b.jsonl", FirstMessage: "b", Modified: now.Add(-time.Hour)},
	}
	var deleted []string
	queue := &postQueue{}
	component := NewSessionSelectorComponent(
		func(SessionListProgress, context.Context) ([]coding.SessionInfo, error) { return sessions, nil },
		func(SessionListProgress, context.Context) ([]coding.SessionInfo, error) { return sessions, nil },
		func(string) {}, func() {}, func() {}, func() {},
		SessionSelectorOptions{
			DeleteSession: func(sessionPath string) SessionDeleteResult {
				deleted = append(deleted, sessionPath)
				return SessionDeleteResult{OK: true, Method: "trash"}
			},
			ScheduleTimer: func(ms int, fn func()) {},
			Post:          queue.Post,
		})
	component.WaitForPendingLoads()
	queue.drain()

	list := component.GetSessionList()
	// Ctrl+D starts the confirmation.
	list.HandleInput("\x04")
	if component.GetHeader().confirmingDeletePath == nil {
		t.Fatal("confirmation not started")
	}
	// Escape cancels it.
	list.HandleInput("\x1b")
	if component.GetHeader().confirmingDeletePath != nil {
		t.Fatal("confirmation not cancelled")
	}
	// Ctrl+D then Enter deletes the second session.
	list.HandleInput("\x1b[B")
	list.HandleInput("\x04")
	list.HandleInput("\r")
	component.WaitForPendingLoads()
	if len(deleted) != 1 || deleted[0] != "/s/b.jsonl" {
		t.Fatalf("deleted = %v", deleted)
	}
	if message := component.GetHeader().statusMessage; message == nil || message.Message != "Session moved to trash" {
		t.Fatalf("status = %+v", message)
	}
}

// The session picker is also the mobile interface (/resume on a phone, or pier
// -r over ssh from Termux): at phone widths upstream's single-line header is
// truncated to the title plus at best one control, and the right-hand metadata
// column squeezes the session's message into a handful of characters. Below
// mobileTerminalWidth the port stacks both — controls on their own lines, the
// metadata under the message — which is a deliberate divergence (D158).

// mobileTestMessage is 36 columns: too wide for a 40-column one-line row beside
// its metadata, comfortable once the metadata moves below it.
const mobileTestMessage = "Fix the parser bug in the loader"

func newMobileSessionList(t *testing.T, width int) *SessionList {
	t.Helper()
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)
	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	t.Cleanup(func() { tui.SetKeybindings(previous) })

	now := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)
	infos := toSessionInfos([]sessionSpecJSON{
		{Path: "/s/one.jsonl", FirstMessage: mobileTestMessage, ModifiedAgoMs: 3 * 3600 * 1000, MessageCount: 3},
		{Path: "/s/two.jsonl", MessageCount: 2, FirstMessage: "Deploy the release to staging", ModifiedAgoMs: 8 * 24 * 3600 * 1000},
	}, now)
	list := NewSessionList(infos, false, SortThreaded, NameFilterAll, appKeybindings.KeybindingsManager, "")
	list.now = func() time.Time { return now }
	list.maxVisible = 4
	return list
}

// TestSessionListUsesTwoLineRowsOnNarrowTerminals: the message gets the full
// width and the metadata moves below it.
// plainLines strips styling so the layout can be asserted on text.
func plainLines(lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		out = append(out, strings.TrimRight(ansiSequenceRe.ReplaceAllString(line, ""), " "))
	}
	return out
}

func TestSessionListUsesTwoLineRowsOnNarrowTerminals(t *testing.T) {
	list := newMobileSessionList(t, 40)
	lines := list.Render(40)
	for _, line := range lines {
		if tui.VisibleWidth(line) > 40 {
			t.Errorf("line wider than the terminal: %q", line)
		}
	}
	rows := plainLines(lines)
	joined := strings.Join(rows, "\n")
	// The message is 36 columns: it does not fit beside the metadata at 40
	// columns, so it is only shown whole once the metadata is below it.
	if !strings.Contains(joined, "› "+mobileTestMessage) {
		t.Errorf("the selected message should keep the full width:\n%s", joined)
	}
	if !strings.Contains(joined, "3 3h") {
		t.Errorf("the metadata is missing from its own line:\n%s", joined)
	}
	for index, row := range rows {
		if !strings.Contains(row, "3 3h") {
			continue
		}
		if index == 0 {
			t.Fatalf("metadata on the message's line:\n%s", joined)
		}
		if !strings.HasPrefix(row, "  3 3h") {
			t.Errorf("metadata line = %q, want it indented under the message", row)
		}
	}
}

// The wide layout is untouched: same one line per session as upstream.
func TestSessionListKeepsOneLineWhenWide(t *testing.T) {
	list := newMobileSessionList(t, 100)
	lines := list.Render(100)
	if len(lines) > 8 {
		t.Fatalf("expected one line per session, got %d lines:\n%s", len(lines), strings.Join(lines, "\n"))
	}
	if !strings.Contains(strings.Join(plainLines(lines), "\n"), "3 3h") {
		t.Fatalf("metadata missing at width 100:\n%s", strings.Join(plainLines(lines), "\n"))
	}
}

// TestSessionSelectorHeaderStacksOnNarrowTerminals: every control stays
// readable instead of the line being cut off.
func TestSessionSelectorHeaderStacksOnNarrowTerminals(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	header := NewSessionSelectorHeader(SessionScopeCurrent, SortThreaded, NameFilterAll, func() {})
	lines := header.Render(40)
	for _, line := range lines {
		if tui.VisibleWidth(line) > 40 {
			t.Errorf("header line wider than the terminal: %q", line)
		}
	}
	joined := strings.Join(plainLines(lines), "\n")
	for _, want := range []string{"Resume Session (Current Folder)", "◉ Current Folder", "Name: All", "Sort: Threaded"} {
		if !strings.Contains(joined, want) {
			t.Errorf("header is missing %q:\n%s", want, joined)
		}
	}
	// The title is its own line, and the controls follow on theirs.
	rows := plainLines(lines)
	if !strings.Contains(rows[0], "Resume Session (Current Folder)") {
		t.Errorf("first line = %q, want the title", rows[0])
	}
	if strings.Contains(rows[0], "Sort:") {
		t.Errorf("the controls should have moved off the title's line: %q", rows[0])
	}
}

// The header at 80 columns is upstream's single line, unchanged.
func TestSessionSelectorHeaderStaysOneLineWhenWide(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	header := NewSessionSelectorHeader(SessionScopeCurrent, SortThreaded, NameFilterAll, func() {})
	lines := plainLines(header.Render(80))
	// At 80 columns upstream cuts the title short rather than moving a control:
	// the title still leads the line and every control follows it.
	if !strings.HasPrefix(lines[0], "Resume Session (Current Fol") || !strings.Contains(lines[0], "Sort: Threaded") {
		t.Fatalf("wide header line = %q, want title and controls together", lines[0])
	}
	if len(lines) < 3 {
		t.Fatalf("wide header = %#v, want the three upstream lines", lines)
	}
}

// TestWrapParts covers the layout helper: one line when the parts fit, more when
// they do not, and never past the width.
func TestWrapParts(t *testing.T) {
	if got := wrapParts([]string{"aa", "bb", "cc"}, " · ", 40); len(got) != 1 || got[0] != "aa · bb · cc" {
		t.Fatalf("fits on one line: %#v", got)
	}
	got := wrapParts([]string{"aaaa", "bbbb", "cccc"}, " · ", 12)
	if len(got) != 2 || got[0] != "aaaa · bbbb" || got[1] != "cccc" {
		t.Fatalf("wrap = %#v", got)
	}
	for _, line := range got {
		if tui.VisibleWidth(line) > 12 {
			t.Errorf("line %q exceeds the width", line)
		}
	}
	if got := wrapParts([]string{"averyveryveryverylongpart"}, " · ", 8); len(got) != 1 || tui.VisibleWidth(got[0]) > 8 {
		t.Fatalf("oversized part = %#v", got)
	}
}

// postQueue is a Post sink for tests without a UI loop: it queues the
// background loader's callbacks so the test can run them on its own goroutine
// after WaitForPendingLoads, never concurrently with Render.
type postQueue struct {
	mu      sync.Mutex
	pending []func()
}

func (q *postQueue) Post(fn func()) {
	q.mu.Lock()
	q.pending = append(q.pending, fn)
	q.mu.Unlock()
}

// drain runs every queued callback, including ones queued while draining.
func (q *postQueue) drain() {
	for {
		q.mu.Lock()
		if len(q.pending) == 0 {
			q.mu.Unlock()
			return
		}
		fn := q.pending[0]
		q.pending = q.pending[1:]
		q.mu.Unlock()
		fn()
	}
}

// TestSessionSelectorApplyStaysOnTheLoop pins the same stage-4 invariant as the
// model selector: the loader worker is a pure producer, so its apply reaches
// the selector only through the Post sink. Running it inline let SetLoading
// mutate the header while the owner rendered it.
func TestSessionSelectorApplyStaysOnTheLoop(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	loader := func(SessionListProgress, context.Context) ([]coding.SessionInfo, error) { return nil, nil }
	component := NewSessionSelectorComponent(loader, loader,
		func(string) {}, func() {}, func() {}, func() {},
		SessionSelectorOptions{ScheduleTimer: func(int, func()) {}})

	var worker sync.WaitGroup
	worker.Add(1)
	go func() {
		defer worker.Done()
		for i := 0; i < 200; i++ {
			component.postApply(func() { component.header.SetLoading(false) })
		}
	}()
	for i := 0; i < 200; i++ {
		_ = component.Render(80)
	}
	worker.Wait()

	// The constructor started the load with the header loading; a dropped apply
	// must leave that as is. An inline apply would have cleared it (and raced the
	// owner's Render).
	if !component.header.loading {
		t.Fatal("a loader apply ran off-loop; it can race the owner's Render")
	}
}
