package interactive

import (
	"context"
	"encoding/json"
	"os"
	"testing"
	"time"

	"github.com/dat267/gpi/coding"
	"github.com/dat267/gpi/tui"
)

// The golden file is generated by running the upstream session selector with
// Node (coding/interactive/testdata/session_golden.txt). Relative ages are
// derived from a per-run "now", so the corpus stores the age offsets.

type sessionSpecJSON struct {
	Path              string `json:"path"`
	ID                string `json:"id"`
	Cwd               string `json:"cwd"`
	Name              string `json:"name"`
	ParentSessionPath string `json:"parentSessionPath"`
	ModifiedAgoMs     int64  `json:"modifiedAgoMs"`
	MessageCount      int    `json:"messageCount"`
	FirstMessage      string `json:"firstMessage"`
	AllMessagesText   string `json:"allMessagesText"`
}

type sessionCaseJSON struct {
	Width                  int               `json:"width"`
	CurrentSessions        []sessionSpecJSON `json:"currentSessions"`
	AllSessions            []sessionSpecJSON `json:"allSessions"`
	CurrentSessionFilePath string            `json:"currentSessionFilePath"`
	Inputs                 []string          `json:"inputs"`
	LoadError              string            `json:"loadError"`
	Progress               []int             `json:"progress"`
	CanRename              *bool             `json:"canRename"`
	ShowRenameHint         *bool             `json:"showRenameHint"`
}

type sessionCorpus struct {
	Cases map[string]sessionCaseJSON `json:"cases"`
}

func toSessionInfos(specs []sessionSpecJSON, now time.Time) []coding.SessionInfo {
	result := make([]coding.SessionInfo, 0, len(specs))
	for _, spec := range specs {
		modified := now.Add(-time.Duration(spec.ModifiedAgoMs) * time.Millisecond)
		result = append(result, coding.SessionInfo{
			Path:              spec.Path,
			ID:                spec.ID,
			Cwd:               spec.Cwd,
			Name:              spec.Name,
			ParentSessionPath: spec.ParentSessionPath,
			Created:           modified,
			Modified:          modified,
			MessageCount:      spec.MessageCount,
			FirstMessage:      spec.FirstMessage,
			AllMessagesText:   spec.AllMessagesText,
		})
	}
	return result
}

// TestSessionSelectorAgainstUpstreamGolden replays the session selector
// renders, callbacks and rename traces.
func TestSessionSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/session_golden.txt")
	data, err := os.ReadFile("testdata/session_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := sessionCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	// The app keybindings must be installed globally, exactly like the
	// interactive mode does (the list reads app.* bindings from there).
	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	for _, label := range sortedKeys(corpus.Cases) {
		spec := corpus.Cases[label]
		// A fixed "now" keeps the relative ages stable while still matching
		// the probe's Date.now()-based offsets.
		now := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)
		current := toSessionInfos(spec.CurrentSessions, now)
		all := toSessionInfos(spec.AllSessions, now)
		if spec.AllSessions == nil {
			all = current
		}

		var events []string
		var renames []string
		currentLoader := func(onProgress SessionListProgress, ctx context.Context) ([]coding.SessionInfo, error) {
			if spec.LoadError != "" {
				return nil, errString(spec.LoadError)
			}
			if len(spec.Progress) == 2 {
				onProgress(spec.Progress[0], spec.Progress[1], nil)
			}
			return current, nil
		}
		allLoader := func(onProgress SessionListProgress, ctx context.Context) ([]coding.SessionInfo, error) {
			if spec.LoadError != "" {
				return nil, errString(spec.LoadError)
			}
			return all, nil
		}

		options := SessionSelectorOptions{
			Keybindings:            appKeybindings.KeybindingsManager,
			CurrentSessionFilePath: spec.CurrentSessionFilePath,
			Now:                    func() time.Time { return now },
			ScheduleTimer:          func(ms int, fn func()) {},
		}
		canRename := true
		if spec.CanRename != nil {
			canRename = *spec.CanRename
		}
		if canRename {
			options.RenameSession = func(sessionPath string, currentName string) error {
				renames = append(renames, sessionPath+"="+currentName)
				return nil
			}
		}
		if spec.ShowRenameHint != nil {
			options.ShowRenameHint = *spec.ShowRenameHint
		}

		component := NewSessionSelectorComponent(currentLoader, allLoader,
			func(sessionPath string) { events = append(events, "select:"+sessionPath) },
			func() { events = append(events, "cancel") },
			func() { events = append(events, "exit") },
			func() {}, options)
		component.WaitForPendingLoads()

		checkEasterGolden(t, golden, label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		for index, input := range spec.Inputs {
			component.HandleInput(input)
			component.WaitForPendingLoads()
			encoded, _ := json.Marshal(input)
			checkEasterGolden(t, golden, label+"+"+itoa(index)+"+"+string(encoded)+"@"+itoa(spec.Width),
				normalizeRender(component.Render(spec.Width)))
		}
		if events == nil {
			events = []string{}
		}
		if renames == nil {
			renames = []string{}
		}
		checkEasterGolden(t, golden, label+"-events", events)
		checkEasterGolden(t, golden, label+"-renames", renames)
	}
}

type errString string

func (e errString) Error() string { return string(e) }

// TestSessionSelectorHelpers covers the pure helpers and the tree building.
func TestSessionSelectorHelpers(t *testing.T) {
	now := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)
	cases := []struct {
		ago  time.Duration
		want string
	}{
		{30 * time.Second, "now"},
		{5 * time.Minute, "5m"},
		{3 * time.Hour, "3h"},
		{2 * 24 * time.Hour, "2d"},
		{20 * 24 * time.Hour, "2w"},
		{45 * 24 * time.Hour, "1mo"},
		{400 * 24 * time.Hour, "1y"},
	}
	for _, testCase := range cases {
		if got := formatSessionDate(now.Add(-testCase.ago), now); got != testCase.want {
			t.Fatalf("age(%v) = %q, want %q", testCase.ago, got, testCase.want)
		}
	}
	if got := shortenSessionPath(""); got != "" {
		t.Fatalf("shorten empty = %q", got)
	}
	if got := shortenSessionPath("/tmp/x"); got != "/tmp/x" {
		t.Fatalf("shorten tmp = %q", got)
	}
	home, _ := os.UserHomeDir()
	if home != "" {
		if got := shortenSessionPath(home + "/x"); got != "~/x" {
			t.Fatalf("shorten home = %q", got)
		}
	}

	sessions := []coding.SessionInfo{
		{Path: "/s/root.jsonl", Modified: now.Add(-time.Hour)},
		{Path: "/s/child.jsonl", ParentSessionPath: "/s/root.jsonl", Modified: now.Add(-2 * time.Hour)},
		{Path: "/s/other.jsonl", Modified: now.Add(-3 * time.Hour)},
		{Path: "/s/orphan.jsonl", ParentSessionPath: "/s/missing.jsonl", Modified: now.Add(-4 * time.Hour)},
	}
	roots := buildSessionTree(sessions)
	if len(roots) != 3 {
		t.Fatalf("roots = %d", len(roots))
	}
	// The root with the most recent activity in its subtree sorts first.
	if roots[0].Session.Path != "/s/root.jsonl" {
		t.Fatalf("first root = %q", roots[0].Session.Path)
	}
	if len(roots[0].Children) != 1 || roots[0].Children[0].Session.Path != "/s/child.jsonl" {
		t.Fatalf("children = %+v", roots[0].Children)
	}
	flat := flattenSessionTree(roots)
	if len(flat) != 4 {
		t.Fatalf("flat = %d", len(flat))
	}
	if flat[0].Depth != 0 || flat[1].Depth != 1 {
		t.Fatalf("depths = %d, %d", flat[0].Depth, flat[1].Depth)
	}
	if flat[1].IsLast != true {
		t.Fatalf("child isLast = %v", flat[1].IsLast)
	}
	if got := (&SessionList{}).buildTreePrefix(flatSessionNode{Depth: 2, IsLast: false, AncestorContinues: []bool{true, false}}); got != "│  "+"   "+"├─ " {
		t.Fatalf("prefix = %q", got)
	}
	if got := stripControlCharacters("a\x01b\x7fc"); got != "a b c" {
		t.Fatalf("strip = %q", got)
	}
}

// TestSessionSelectorDeleteFlow checks the confirmation and deletion plumbing
// with an injected deleter (D102).
func TestSessionSelectorDeleteFlow(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	now := time.Now()
	sessions := []coding.SessionInfo{
		{Path: "/s/a.jsonl", FirstMessage: "a", Modified: now},
		{Path: "/s/b.jsonl", FirstMessage: "b", Modified: now.Add(-time.Hour)},
	}
	var deleted []string
	component := NewSessionSelectorComponent(
		func(SessionListProgress, context.Context) ([]coding.SessionInfo, error) { return sessions, nil },
		func(SessionListProgress, context.Context) ([]coding.SessionInfo, error) { return sessions, nil },
		func(string) {}, func() {}, func() {}, func() {},
		SessionSelectorOptions{
			DeleteSession: func(sessionPath string) SessionDeleteResult {
				deleted = append(deleted, sessionPath)
				return SessionDeleteResult{OK: true, Method: "trash"}
			},
			ScheduleTimer: func(ms int, fn func()) {},
		})
	component.WaitForPendingLoads()

	list := component.GetSessionList()
	// Ctrl+D starts the confirmation.
	list.HandleInput("\x04")
	if component.GetHeader().confirmingDeletePath == nil {
		t.Fatal("confirmation not started")
	}
	// Escape cancels it.
	list.HandleInput("\x1b")
	if component.GetHeader().confirmingDeletePath != nil {
		t.Fatal("confirmation not cancelled")
	}
	// Ctrl+D then Enter deletes the second session.
	list.HandleInput("\x1b[B")
	list.HandleInput("\x04")
	list.HandleInput("\r")
	component.WaitForPendingLoads()
	if len(deleted) != 1 || deleted[0] != "/s/b.jsonl" {
		t.Fatalf("deleted = %v", deleted)
	}
	if message := component.GetHeader().statusMessage; message == nil || message.Message != "Session moved to trash" {
		t.Fatalf("status = %+v", message)
	}
}
