package interactive

import (
	"encoding/json"
	"os"
	"testing"
	"time"

	"github.com/dat267/gpi/coding"
	"github.com/dat267/gpi/tui"
)

// The golden file is generated by running the upstream tree selector with Node
// (coding/interactive/testdata/tree_golden.txt). Both sides write the same
// session JSONL fixture and load it with their session manager, so the tree
// projection also verifies GetTree().

const treeProbeSessionPath = "/tmp/gpi-tree/session.jsonl"

type treeCaseJSON struct {
	Width             int      `json:"width"`
	TerminalHeight    int      `json:"terminalHeight"`
	CurrentLeafID     *string  `json:"currentLeafId"`
	InitialSelectedID *string  `json:"initialSelectedId"`
	InitialFilterMode string   `json:"initialFilterMode"`
	Inputs            []string `json:"inputs"`
}

type treeCorpus struct {
	SessionJSONL string                  `json:"sessionJsonl"`
	Cases        map[string]treeCaseJSON `json:"cases"`
}

// projectTree serializes the tree like the upstream probe does.
func projectTree(nodes []*coding.SessionTreeNode) []any {
	result := make([]any, 0, len(nodes))
	for _, node := range nodes {
		var label any
		if node.HasLabel {
			label = node.Label
		}
		var labelTimestamp any
		if node.HasLabel && node.LabelTimestamp != "" {
			labelTimestamp = node.LabelTimestamp
		}
		var parentID any
		if node.Entry.ParentID != nil {
			parentID = *node.Entry.ParentID
		}
		result = append(result, map[string]any{
			"id":             node.Entry.ID,
			"parentId":       parentID,
			"type":           node.Entry.Type,
			"label":          label,
			"labelTimestamp": labelTimestamp,
			"children":       projectTree(node.Children),
		})
	}
	return result
}

// TestTreeSelectorAgainstUpstreamGolden replays the tree projection and the
// tree selector renders.
func TestTreeSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/tree_golden.txt")
	data, err := os.ReadFile("testdata/tree_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := treeCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	if err := os.MkdirAll("/tmp/gpi-tree", 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(treeProbeSessionPath, []byte(corpus.SessionJSONL), 0o644); err != nil {
		t.Fatalf("write session: %v", err)
	}

	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	// A fixed clock keeps the label timestamps deterministic. The fixture
	// timestamps are from a different year, so the rendered form only depends
	// on the local timezone (shared by both sides).
	fixedNow := time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)

	for _, label := range sortedKeys(corpus.Cases) {
		spec := corpus.Cases[label]
		manager, err := coding.OpenSession(treeProbeSessionPath, "", "")
		if err != nil {
			t.Fatalf("open session: %v", err)
		}
		tree := manager.GetTree()
		checkEasterGolden(t, golden, label+"-tree", projectTree(tree))

		terminalHeight := spec.TerminalHeight
		if terminalHeight == 0 {
			terminalHeight = 40
		}
		component := NewTreeSelectorComponent(tree, spec.CurrentLeafID, terminalHeight,
			func(string) {}, func() {}, TreeSelectorOptions{
				Now:               func() time.Time { return fixedNow },
				ScheduleTimer:     func(ms int, fn func()) {},
				InitialSelectedID: spec.InitialSelectedID,
				InitialFilterMode: spec.InitialFilterMode,
			})

		checkEasterGolden(t, golden, label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		for index, input := range spec.Inputs {
			component.HandleInput(input)
			encoded, _ := json.Marshal(input)
			checkEasterGolden(t, golden, label+"+"+itoa(index)+"+"+string(encoded)+"@"+itoa(spec.Width),
				normalizeRender(component.Render(spec.Width)))
		}
	}
}

// TestTreeSelectorHelpers covers the pure tree helpers.
func TestTreeSelectorHelpers(t *testing.T) {
	themes := []string{}
	_ = themes

	rows := []horizontalViewportRow{
		{Gutter: "  ", Body: "0123456789", AnchorCol: 0, BodyWidth: 10, IsSelected: true},
		{Gutter: "  ", Body: "abcdefghij", AnchorCol: 4, BodyWidth: 10},
	}
	lines := renderHorizontalViewport(rows, 8)
	if len(lines) != 2 {
		t.Fatalf("lines = %d", len(lines))
	}
	if tui.VisibleWidth(lines[0]) > 8 || tui.VisibleWidth(lines[1]) > 8 {
		t.Fatalf("width overflow: %q %q", lines[0], lines[1])
	}
	if lines[0] != "  012345\x1b[0m" {
		t.Fatalf("unpanned = %q", lines[0])
	}

	// Panning: a long selected row with a far anchor scrolls the body.
	longRows := []horizontalViewportRow{
		{Gutter: "> ", Body: "0123456789012345678901234567890123456789", AnchorCol: 30, BodyWidth: 40, IsSelected: true},
	}
	panned := renderHorizontalViewport(longRows, 20)
	if panned[0][:2] != "> " {
		t.Fatalf("gutter lost: %q", panned[0])
	}
	if tui.VisibleWidth(panned[0]) > 20 {
		t.Fatalf("panned overflow: %q", panned[0])
	}

	if got := compactRawKeys([]string{"up", "down"}); got != "up/down" {
		t.Fatalf("compactRawKeys = %q", got)
	}
	if got := compactRawKeys([]string{"ctrl+a", "ctrl+b"}); got != "ctrl+a/b" {
		t.Fatalf("compactRawKeys = %q", got)
	}
	if got := compactRawKeys([]string{"pageUp"}); got != "pageUp" {
		t.Fatalf("compactRawKeys = %q", got)
	}
	if got := replaceWholeWords("pgup/down pageUp pageDown"); got != "pgup/↓ pgup pgdn" {
		t.Fatalf("replaceWholeWords = %q", got)
	}
	if got := toggleFilterMode(FilterUserOnly, FilterUserOnly); got != FilterDefault {
		t.Fatalf("toggle = %q", got)
	}
	if got := toggleFilterMode(FilterDefault, FilterUserOnly); got != FilterUserOnly {
		t.Fatalf("toggle = %q", got)
	}
	if got := indexOfFilterMode(FilterLabeledOnly); got != 3 {
		t.Fatalf("index = %d", got)
	}
}

// TestTreeSelectorLabels checks the label editing flow.
func TestTreeSelectorLabels(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	appKeybindings := NewAppKeybindingsManager(nil, "")
	previous := tui.GetKeybindings()
	tui.SetKeybindings(appKeybindings.KeybindingsManager)
	defer tui.SetKeybindings(previous)

	entry := coding.SessionEntry{Type: "message"}
	entry.ID = "a"
	entry.Message = json.RawMessage(`{"role":"user","content":"hello"}`)
	tree := []*coding.SessionTreeNode{{Entry: entry}}

	var changes []string
	component := NewTreeSelectorComponent(tree, nil, 20, func(string) {}, func() {}, TreeSelectorOptions{
		OnLabelChange: func(entryID string, label *string) {
			if label == nil {
				changes = append(changes, entryID+"=nil")
				return
			}
			changes = append(changes, entryID+"="+*label)
		},
		ScheduleTimer: func(ms int, fn func()) {},
	})
	list := component.GetTreeList()

	// Shift+L opens the label input.
	component.HandleInput("L")
	if component.labelInput == nil {
		t.Fatal("label input not shown")
	}
	// Type a label and submit.
	for _, char := range "keep" {
		component.HandleInput(string(char))
	}
	component.HandleInput("\r")
	if component.labelInput != nil {
		t.Fatal("label input not hidden")
	}
	if len(changes) != 1 || changes[0] != "a=keep" {
		t.Fatalf("changes = %v", changes)
	}
	if !list.flatNodes[0].Node.HasLabel || list.flatNodes[0].Node.Label != "keep" {
		t.Fatalf("label not applied: %+v", list.flatNodes[0].Node)
	}

	// Re-open, clear with forward deletes and submit: the label is removed.
	component.HandleInput("L")
	for range "keep" {
		component.HandleInput("\x1b[3~")
	}
	component.HandleInput("\r")
	if len(changes) != 2 || changes[1] != "a=nil" {
		t.Fatalf("changes = %v", changes)
	}
	if list.flatNodes[0].Node.HasLabel {
		t.Fatal("label not cleared")
	}

	// Escape cancels without changes.
	component.HandleInput("L")
	component.HandleInput("\x1b")
	if component.labelInput != nil {
		t.Fatal("label input not cancelled")
	}
	if len(changes) != 2 {
		t.Fatalf("changes = %v", changes)
	}
}

// TestTreeSelectorEmptyAutoCancel checks the empty-tree cancel timer.
func TestTreeSelectorEmptyAutoCancel(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	var fired []func()
	canceled := false
	NewTreeSelectorComponent(nil, nil, 20, func(string) {}, func() { canceled = true }, TreeSelectorOptions{
		ScheduleTimer: func(ms int, fn func()) { fired = append(fired, fn) },
	})
	if len(fired) != 1 {
		t.Fatalf("timers = %d", len(fired))
	}
	fired[0]()
	if !canceled {
		t.Fatal("cancel not fired")
	}
}
