package interactive

import (
	"os"
	"testing"
	"time"
)

// TestMain pins the process timezone. The upstream-derived goldens were
// generated by driving the TypeScript with Node at UTC+7 (tree-selector label
// timestamps render in local time, e.g. "20/3/4 12:06"); CI runs in UTC and
// would otherwise see "05:06". The fixed zone needs no tzdata.
func TestMain(m *testing.M) {
	time.Local = time.FixedZone("golden", 7*60*60)
	os.Exit(m.Run())
}
