package coding

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The golden file is generated by running the upstream changelog utilities and
// footer data provider with Node (coding/testdata/core_golden.txt).

func loadCoreGolden(t *testing.T) map[string]string {
	t.Helper()
	data, err := os.ReadFile("testdata/core_golden.txt")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	values := map[string]string{}
	for _, line := range splitGoldenLines(string(data)) {
		key, value, ok := splitGoldenLine(line)
		if !ok {
			t.Fatalf("bad golden line %q", line)
		}
		values[key] = value
	}
	return values
}

func splitGoldenLines(content string) []string {
	var lines []string
	current := ""
	for _, r := range content {
		if r == '\n' {
			lines = append(lines, current)
			current = ""
			continue
		}
		current += string(r)
	}
	if current != "" {
		lines = append(lines, current)
	}
	return lines
}

func splitGoldenLine(line string) (string, string, bool) {
	for i := 0; i+4 <= len(line); i++ {
		if line[i:i+4] == " => " {
			key := line[:i]
			if len(key) > 2 && key[:2] == "x " {
				key = key[2:]
			}
			return key, line[i+4:], true
		}
	}
	return "", "", false
}

func checkCoreGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	encoded, err := json.Marshal(got)
	if err != nil {
		t.Fatalf("marshal %s: %v", label, err)
	}
	if string(encoded) != want {
		t.Fatalf("%s:\n got %s\nwant %s", label, encoded, want)
	}
}

// TestChangelogAgainstUpstreamGolden replays the changelog link/parse helpers.
func TestChangelogAgainstUpstreamGolden(t *testing.T) {
	golden := loadCoreGolden(t)
	data, err := os.ReadFile("testdata/core_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var corpus struct {
		Links map[string]struct {
			Markdown string `json:"markdown"`
			Version  string `json:"version"`
		} `json:"links"`
		Changelog   string             `json:"changelog"`
		LastVersion string             `json:"lastVersion"`
		Compare     [][]ChangelogEntry `json:"compare"`
	}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedCoreKeys(corpus.Links) {
		spec := corpus.Links[label]
		checkCoreGolden(t, golden, "links "+label, NormalizeChangelogLinks(spec.Markdown, spec.Version))
	}

	if err := os.MkdirAll("/tmp/pier-core", 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	changelogPath := "/tmp/pier-core/CHANGELOG.md"
	if err := os.WriteFile(changelogPath, []byte(corpus.Changelog), 0o644); err != nil {
		t.Fatalf("write changelog: %v", err)
	}
	entries := ParseChangelog(changelogPath)
	checkCoreGolden(t, golden, "changelog entries", entries)
	checkCoreGolden(t, golden, "changelog new", GetNewChangelogEntries(entries, corpus.LastVersion))
	comparisons := make([]int, 0, len(corpus.Compare))
	for _, pair := range corpus.Compare {
		comparisons = append(comparisons, CompareChangelogVersions(pair[0], pair[1]))
	}
	checkCoreGolden(t, golden, "changelog compare", comparisons)
	missing := ParseChangelog("/tmp/pier-core/nope.md")
	if missing == nil {
		missing = []ChangelogEntry{}
	}
	checkCoreGolden(t, golden, "changelog missing", missing)
}

// TestFooterDataProviderAgainstUpstreamGolden replays the footer data source.
func TestFooterDataProviderAgainstUpstreamGolden(t *testing.T) {
	golden := loadCoreGolden(t)

	repo := "/tmp/pier-core/repo"
	detached := "/tmp/pier-core/detached"
	plain := "/tmp/pier-core/plain"
	for _, dir := range []string{filepath.Join(repo, ".git"), filepath.Join(detached, ".git"), plain} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
	}
	writeFile(t, filepath.Join(repo, ".git", "HEAD"), "ref: refs/heads/feature/x\n")
	writeFile(t, filepath.Join(detached, ".git", "HEAD"), "0123456789abcdef0123456789abcdef01234567\n")

	for _, testCase := range []struct{ label, cwd string }{
		{"repo", repo}, {"detached", detached}, {"plain", plain},
	} {
		provider := NewFooterDataProvider(testCase.cwd, FooterDataProviderOptions{DisableWatch: true})

		branch, ok := provider.GetGitBranch()
		var branchValue any
		if ok {
			branchValue = branch
		}
		checkCoreGolden(t, golden, "footer "+testCase.label+" branch", branchValue)

		status := "v"
		provider.SetExtensionStatus("k", &status)
		provider.SetAvailableProviderCount(3)
		checkCoreGolden(t, golden, "footer "+testCase.label+" statuses", statusPairs(provider.GetExtensionStatuses()))
		checkCoreGolden(t, golden, "footer "+testCase.label+" count", provider.GetAvailableProviderCount())
		provider.SetExtensionStatus("k", nil)
		checkCoreGolden(t, golden, "footer "+testCase.label+" cleared", statusPairs(provider.GetExtensionStatuses()))

		changes := 0
		unsubscribe := provider.OnBranchChange(func() { changes++ })
		provider.SetCwd(plain)
		provider.SetCwd(plain)
		afterBranch, afterOK := provider.GetGitBranch()
		var afterValue any
		if afterOK {
			afterValue = afterBranch
		}
		checkCoreGolden(t, golden, "footer "+testCase.label+" changes", []any{changes, afterValue})
		unsubscribe()
		provider.Dispose()
	}
}

func statusPairs(statuses map[string]string) [][2]string {
	pairs := make([][2]string, 0, len(statuses))
	for key, value := range statuses {
		pairs = append(pairs, [2]string{key, value})
	}
	return pairs
}

func writeFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func sortedCoreKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j-1] > keys[j]; j-- {
			keys[j-1], keys[j] = keys[j], keys[j-1]
		}
	}
	return keys
}
